// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "des_dec.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic des_dec::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic des_dec::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> des_dec::ap_ST_fsm_state1 = "1";
const sc_lv<21> des_dec::ap_ST_fsm_state2 = "10";
const sc_lv<21> des_dec::ap_ST_fsm_state3 = "100";
const sc_lv<21> des_dec::ap_ST_fsm_state4 = "1000";
const sc_lv<21> des_dec::ap_ST_fsm_state5 = "10000";
const sc_lv<21> des_dec::ap_ST_fsm_state6 = "100000";
const sc_lv<21> des_dec::ap_ST_fsm_state7 = "1000000";
const sc_lv<21> des_dec::ap_ST_fsm_state8 = "10000000";
const sc_lv<21> des_dec::ap_ST_fsm_state9 = "100000000";
const sc_lv<21> des_dec::ap_ST_fsm_state10 = "1000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state11 = "10000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state12 = "100000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<21> des_dec::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> des_dec::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> des_dec::ap_const_lv32_1 = "1";
const sc_lv<1> des_dec::ap_const_lv1_0 = "0";
const sc_lv<1> des_dec::ap_const_lv1_1 = "1";
const sc_lv<32> des_dec::ap_const_lv32_2 = "10";
const sc_lv<32> des_dec::ap_const_lv32_3 = "11";
const sc_lv<32> des_dec::ap_const_lv32_4 = "100";
const sc_lv<32> des_dec::ap_const_lv32_5 = "101";
const sc_lv<32> des_dec::ap_const_lv32_6 = "110";
const sc_lv<32> des_dec::ap_const_lv32_7 = "111";
const sc_lv<32> des_dec::ap_const_lv32_8 = "1000";
const sc_lv<32> des_dec::ap_const_lv32_9 = "1001";
const sc_lv<32> des_dec::ap_const_lv32_A = "1010";
const sc_lv<32> des_dec::ap_const_lv32_B = "1011";
const sc_lv<32> des_dec::ap_const_lv32_C = "1100";
const sc_lv<32> des_dec::ap_const_lv32_D = "1101";
const sc_lv<32> des_dec::ap_const_lv32_E = "1110";
const sc_lv<32> des_dec::ap_const_lv32_F = "1111";
const sc_lv<32> des_dec::ap_const_lv32_11 = "10001";
const sc_lv<32> des_dec::ap_const_lv32_12 = "10010";
const sc_lv<32> des_dec::ap_const_lv32_13 = "10011";
const sc_lv<32> des_dec::ap_const_lv32_14 = "10100";
const sc_lv<64> des_dec::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<7> des_dec::ap_const_lv7_0 = "0000000";
const sc_lv<6> des_dec::ap_const_lv6_0 = "000000";
const sc_lv<5> des_dec::ap_const_lv5_0 = "00000";
const sc_lv<4> des_dec::ap_const_lv4_0 = "0000";
const sc_lv<32> des_dec::ap_const_lv32_10 = "10000";
const sc_lv<7> des_dec::ap_const_lv7_40 = "1000000";
const sc_lv<6> des_dec::ap_const_lv6_1 = "1";
const sc_lv<6> des_dec::ap_const_lv6_2 = "10";
const sc_lv<6> des_dec::ap_const_lv6_3 = "11";
const sc_lv<7> des_dec::ap_const_lv7_4 = "100";
const sc_lv<32> des_dec::ap_const_lv32_20 = "100000";
const sc_lv<32> des_dec::ap_const_lv32_3F = "111111";
const sc_lv<6> des_dec::ap_const_lv6_38 = "111000";
const sc_lv<32> des_dec::ap_const_lv32_1C = "11100";
const sc_lv<32> des_dec::ap_const_lv32_37 = "110111";
const sc_lv<5> des_dec::ap_const_lv5_10 = "10000";
const sc_lv<5> des_dec::ap_const_lv5_1 = "1";
const sc_lv<5> des_dec::ap_const_lv5_F = "1111";
const sc_lv<5> des_dec::ap_const_lv5_8 = "1000";
const sc_lv<32> des_dec::ap_const_lv32_1A = "11010";
const sc_lv<32> des_dec::ap_const_lv32_1B = "11011";
const sc_lv<6> des_dec::ap_const_lv6_30 = "110000";
const sc_lv<6> des_dec::ap_const_lv6_20 = "100000";
const sc_lv<4> des_dec::ap_const_lv4_8 = "1000";
const sc_lv<4> des_dec::ap_const_lv4_1 = "1";
const sc_lv<3> des_dec::ap_const_lv3_0 = "000";
const sc_lv<2> des_dec::ap_const_lv2_0 = "00";
const sc_lv<6> des_dec::ap_const_lv6_2A = "101010";
const sc_lv<6> des_dec::ap_const_lv6_2B = "101011";
const sc_lv<48> des_dec::ap_const_lv48_840000000000 = "100001000000000000000000000000000000000000000000";
const sc_lv<47> des_dec::ap_const_lv47_780000000000 = "11110000000000000000000000000000000000000000000";
const sc_lv<7> des_dec::ap_const_lv7_1 = "1";
const bool des_dec::ap_const_boolean_1 = true;

des_dec::des_dec(sc_module_name name) : sc_module(name), mVcdFile(0) {
    IP_U = new des_dec_IP("IP_U");
    IP_U->clk(ap_clk);
    IP_U->reset(ap_rst);
    IP_U->address0(IP_address0);
    IP_U->ce0(IP_ce0);
    IP_U->q0(IP_q0);
    IP_U->address1(IP_address1);
    IP_U->ce1(IP_ce1);
    IP_U->q1(IP_q1);
    IP_U->address2(IP_address2);
    IP_U->ce2(IP_ce2);
    IP_U->q2(IP_q2);
    IP_U->address3(IP_address3);
    IP_U->ce3(IP_ce3);
    IP_U->q3(IP_q3);
    PC1_U = new des_dec_PC1("PC1_U");
    PC1_U->clk(ap_clk);
    PC1_U->reset(ap_rst);
    PC1_U->address0(PC1_address0);
    PC1_U->ce0(PC1_ce0);
    PC1_U->q0(PC1_q0);
    PC2_U = new des_dec_PC2("PC2_U");
    PC2_U->clk(ap_clk);
    PC2_U->reset(ap_rst);
    PC2_U->address0(PC2_address0);
    PC2_U->ce0(PC2_ce0);
    PC2_U->q0(PC2_q0);
    E_U = new des_dec_E("E_U");
    E_U->clk(ap_clk);
    E_U->reset(ap_rst);
    E_U->address0(E_address0);
    E_U->ce0(E_ce0);
    E_U->q0(E_q0);
    S_U = new des_dec_S("S_U");
    S_U->clk(ap_clk);
    S_U->reset(ap_rst);
    S_U->address0(S_address0);
    S_U->ce0(S_ce0);
    S_U->q0(S_q0);
    P_U = new des_dec_P("P_U");
    P_U->clk(ap_clk);
    P_U->reset(ap_rst);
    P_U->address0(P_address0);
    P_U->ce0(P_ce0);
    P_U->q0(P_q0);
    PI_U = new des_dec_PI("PI_U");
    PI_U->clk(ap_clk);
    PI_U->reset(ap_rst);
    PI_U->address0(PI_address0);
    PI_U->ce0(PI_ce0);
    PI_U->q0(PI_q0);
    sub_key_U = new des_dec_sub_key("sub_key_U");
    sub_key_U->clk(ap_clk);
    sub_key_U->reset(ap_rst);
    sub_key_U->address0(sub_key_address0);
    sub_key_U->ce0(sub_key_ce0);
    sub_key_U->we0(sub_key_we0);
    sub_key_U->d0(sub_key_load_1_reg_404);
    sub_key_U->q0(sub_key_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C_2_fu_852_p3);
    sensitive << ( trunc_ln203_fu_838_p1 );
    sensitive << ( tmp_3_fu_842_p4 );

    SC_METHOD(thread_C_3_fu_904_p3);
    sensitive << ( trunc_ln197_fu_900_p1 );
    sensitive << ( tmp_2_fu_892_p3 );

    SC_METHOD(thread_D_1_fu_740_p1);
    sensitive << ( permuted_choice_1_0_reg_371 );

    SC_METHOD(thread_D_2_fu_874_p3);
    sensitive << ( trunc_ln204_fu_860_p1 );
    sensitive << ( tmp_s_fu_864_p4 );

    SC_METHOD(thread_D_3_fu_924_p3);
    sensitive << ( trunc_ln198_fu_920_p1 );
    sensitive << ( tmp_4_fu_912_p3 );

    SC_METHOD(thread_E_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln229_fu_1039_p1 );

    SC_METHOD(thread_E_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_IP_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln174_fu_554_p1 );

    SC_METHOD(thread_IP_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln174_5_fu_573_p1 );

    SC_METHOD(thread_IP_address2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln174_6_fu_584_p1 );

    SC_METHOD(thread_IP_address3);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln174_7_fu_595_p1 );

    SC_METHOD(thread_IP_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_IP_ce1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_IP_ce2);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_IP_ce3);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_PC1_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln184_1_fu_721_p1 );

    SC_METHOD(thread_PC1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_PC2_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln218_fu_972_p1 );

    SC_METHOD(thread_PC2_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_PI_address0);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( zext_ln270_1_fu_1415_p1 );

    SC_METHOD(thread_PI_ce0);
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_P_address0);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln254_fu_1361_p1 );

    SC_METHOD(thread_P_ce0);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_R_1_fu_1370_p2);
    sensitive << ( L_0_reg_437 );
    sensitive << ( f_function_res_0_reg_495 );

    SC_METHOD(thread_R_fu_616_p1);
    sensitive << ( init_perm_res_0_0_reg_349 );

    SC_METHOD(thread_S_address0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( sext_ln246_3_fu_1328_p1 );

    SC_METHOD(thread_S_ce0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_add_ln171_fu_600_p2);
    sensitive << ( i_0_0_reg_360 );

    SC_METHOD(thread_add_ln246_1_fu_1322_p2);
    sensitive << ( sext_ln246_2_fu_1306_p1 );
    sensitive << ( zext_ln246_fu_1318_p1 );

    SC_METHOD(thread_add_ln246_fu_1300_p2);
    sensitive << ( sext_ln246_1_fu_1296_p1 );
    sensitive << ( sext_ln246_fu_1288_p1 );

    SC_METHOD(thread_and_ln240_fu_1216_p2);
    sensitive << ( xor_ln232_1_reg_1642 );
    sensitive << ( lshr_ln240_fu_1210_p2 );

    SC_METHOD(thread_and_ln243_fu_1264_p2);
    sensitive << ( xor_ln232_reg_1637 );
    sensitive << ( lshr_ln243_fu_1258_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln267_fu_1403_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln267_fu_1403_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln267_fu_1403_p2 );
    sensitive << ( inv_init_perm_res_0_reg_528 );

    SC_METHOD(thread_empty_12_fu_796_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln192_fu_784_p2 );
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_empty_13_fu_802_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln192_fu_784_p2 );
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_empty_14_fu_808_p2);
    sensitive << ( empty_13_fu_802_p2 );
    sensitive << ( empty_12_fu_796_p2 );

    SC_METHOD(thread_empty_15_fu_814_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln192_fu_784_p2 );
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_empty_16_fu_820_p2);
    sensitive << ( empty_15_fu_814_p2 );
    sensitive << ( empty_14_fu_808_p2 );

    SC_METHOD(thread_empty_17_fu_826_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln192_fu_784_p2 );
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_empty_18_fu_832_p2);
    sensitive << ( empty_17_fu_826_p2 );
    sensitive << ( empty_16_fu_820_p2 );

    SC_METHOD(thread_empty_9_fu_559_p1);
    sensitive << ( i_0_0_reg_360 );

    SC_METHOD(thread_f_function_res_fu_1396_p3);
    sensitive << ( trunc_ln254_1_reg_1693 );
    sensitive << ( trunc_ln254_fu_1392_p1 );

    SC_METHOD(thread_i_5_fu_1409_p2);
    sensitive << ( i_4_reg_517 );

    SC_METHOD(thread_i_6_fu_790_p2);
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_i_7_fu_1013_p2);
    sensitive << ( i_3_reg_448 );

    SC_METHOD(thread_i_fu_715_p2);
    sensitive << ( i_1_reg_382 );

    SC_METHOD(thread_icmp_ln171_fu_548_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_0_reg_360 );

    SC_METHOD(thread_icmp_ln182_fu_709_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_1_reg_382 );

    SC_METHOD(thread_icmp_ln192_fu_784_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_icmp_ln216_fu_960_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( j_0_reg_416 );

    SC_METHOD(thread_icmp_ln223_fu_1007_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i_3_reg_448 );

    SC_METHOD(thread_icmp_ln227_fu_1027_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( j_1_reg_472 );

    SC_METHOD(thread_icmp_ln235_fu_1115_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( j_2_reg_483 );

    SC_METHOD(thread_icmp_ln252_fu_1349_p2);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( j_3_reg_506 );

    SC_METHOD(thread_icmp_ln267_fu_1403_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( i_4_reg_517 );

    SC_METHOD(thread_inv_init_perm_res_fu_1443_p3);
    sensitive << ( trunc_ln270_1_reg_1721 );
    sensitive << ( trunc_ln270_fu_1439_p1 );

    SC_METHOD(thread_j_4_fu_966_p2);
    sensitive << ( j_0_reg_416 );

    SC_METHOD(thread_j_5_fu_1121_p2);
    sensitive << ( j_2_reg_483 );

    SC_METHOD(thread_j_6_fu_1355_p2);
    sensitive << ( j_3_reg_506 );

    SC_METHOD(thread_j_fu_1033_p2);
    sensitive << ( j_1_reg_472 );

    SC_METHOD(thread_lshr_ln174_1_fu_649_p2);
    sensitive << ( input_r );
    sensitive << ( zext_ln174_1_fu_645_p1 );

    SC_METHOD(thread_lshr_ln174_2_fu_668_p2);
    sensitive << ( input_r );
    sensitive << ( zext_ln174_2_fu_664_p1 );

    SC_METHOD(thread_lshr_ln174_3_fu_687_p2);
    sensitive << ( input_r );
    sensitive << ( zext_ln174_3_fu_683_p1 );

    SC_METHOD(thread_lshr_ln174_fu_630_p2);
    sensitive << ( input_r );
    sensitive << ( zext_ln174_4_fu_626_p1 );

    SC_METHOD(thread_lshr_ln184_fu_768_p2);
    sensitive << ( key );
    sensitive << ( zext_ln184_fu_764_p1 );

    SC_METHOD(thread_lshr_ln218_fu_991_p2);
    sensitive << ( tmp_9_reg_1573 );
    sensitive << ( zext_ln218_1_fu_987_p1 );

    SC_METHOD(thread_lshr_ln229_fu_1065_p2);
    sensitive << ( temp_reg_427 );
    sensitive << ( zext_ln229_1_fu_1061_p1 );

    SC_METHOD(thread_lshr_ln240_1_fu_1224_p2);
    sensitive << ( and_ln240_fu_1216_p2 );
    sensitive << ( zext_ln240_6_fu_1221_p1 );

    SC_METHOD(thread_lshr_ln240_fu_1210_p2);
    sensitive << ( zext_ln240_4_fu_1206_p1 );

    SC_METHOD(thread_lshr_ln243_1_fu_1272_p2);
    sensitive << ( and_ln243_fu_1264_p2 );
    sensitive << ( zext_ln243_fu_1269_p1 );

    SC_METHOD(thread_lshr_ln243_fu_1258_p2);
    sensitive << ( zext_ln240_3_fu_1202_p1 );

    SC_METHOD(thread_lshr_ln254_fu_1386_p2);
    sensitive << ( s_output_1_fu_188 );
    sensitive << ( zext_ln254_1_fu_1382_p1 );

    SC_METHOD(thread_lshr_ln270_fu_1434_p2);
    sensitive << ( pre_output_reg_1609 );
    sensitive << ( zext_ln270_fu_1430_p1 );

    SC_METHOD(thread_or_ln171_1_fu_578_p2);
    sensitive << ( empty_9_fu_559_p1 );

    SC_METHOD(thread_or_ln171_2_fu_589_p2);
    sensitive << ( empty_9_fu_559_p1 );

    SC_METHOD(thread_or_ln171_fu_563_p2);
    sensitive << ( empty_9_fu_559_p1 );

    SC_METHOD(thread_or_ln1_fu_1000_p3);
    sensitive << ( trunc_ln218_1_reg_1591 );
    sensitive << ( trunc_ln218_fu_996_p1 );

    SC_METHOD(thread_or_ln241_fu_1242_p2);
    sensitive << ( tmp_5_fu_1234_p3 );
    sensitive << ( trunc_ln240_1_fu_1230_p1 );

    SC_METHOD(thread_or_ln_fu_696_p6);
    sensitive << ( trunc_ln173_reg_1471 );
    sensitive << ( trunc_ln174_fu_635_p1 );
    sensitive << ( trunc_ln171_fu_654_p1 );
    sensitive << ( trunc_ln174_1_fu_673_p1 );
    sensitive << ( trunc_ln174_2_fu_692_p1 );

    SC_METHOD(thread_permuted_choice_1_fu_777_p3);
    sensitive << ( trunc_ln184_1_reg_1524 );
    sensitive << ( trunc_ln184_fu_773_p1 );

    SC_METHOD(thread_pre_output_fu_1019_p3);
    sensitive << ( temp_reg_427 );
    sensitive << ( L_0_reg_437 );

    SC_METHOD(thread_s_input_fu_1079_p3);
    sensitive << ( trunc_ln229_1_fu_1075_p1 );
    sensitive << ( trunc_ln229_fu_1071_p1 );

    SC_METHOD(thread_s_output_fu_1336_p3);
    sensitive << ( S_q0 );
    sensitive << ( trunc_ln246_1_fu_1332_p1 );

    SC_METHOD(thread_sext_ln240_fu_1199_p1);
    sensitive << ( sub_ln240_reg_1655 );

    SC_METHOD(thread_sext_ln246_1_fu_1296_p1);
    sensitive << ( trunc_ln246_fu_1292_p1 );

    SC_METHOD(thread_sext_ln246_2_fu_1306_p1);
    sensitive << ( add_ln246_fu_1300_p2 );

    SC_METHOD(thread_sext_ln246_3_fu_1328_p1);
    sensitive << ( add_ln246_1_reg_1670 );

    SC_METHOD(thread_sext_ln246_fu_1288_p1);
    sensitive << ( tmp_7_fu_1278_p4 );

    SC_METHOD(thread_shl_ln240_1_fu_1163_p3);
    sensitive << ( trunc_ln240_fu_1127_p1 );

    SC_METHOD(thread_shl_ln240_fu_1143_p2);
    sensitive << ( j_2_reg_483 );

    SC_METHOD(thread_shl_ln_fu_1131_p3);
    sensitive << ( trunc_ln240_fu_1127_p1 );

    SC_METHOD(thread_sub_key_address0);
    sensitive << ( sub_key_addr_reg_1561 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln232_fu_1050_p1 );

    SC_METHOD(thread_sub_key_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sub_key_we0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_sub_ln174_1_fu_639_p2);
    sensitive << ( IP_q1 );

    SC_METHOD(thread_sub_ln174_2_fu_658_p2);
    sensitive << ( IP_q2 );

    SC_METHOD(thread_sub_ln174_3_fu_677_p2);
    sensitive << ( IP_q3 );

    SC_METHOD(thread_sub_ln174_fu_620_p2);
    sensitive << ( IP_q0 );

    SC_METHOD(thread_sub_ln184_fu_758_p2);
    sensitive << ( zext_ln184_2_fu_754_p1 );

    SC_METHOD(thread_sub_ln218_fu_981_p2);
    sensitive << ( PC2_q0 );

    SC_METHOD(thread_sub_ln229_fu_1055_p2);
    sensitive << ( E_q0 );

    SC_METHOD(thread_sub_ln232_fu_1044_p2);
    sensitive << ( i_3_reg_448 );

    SC_METHOD(thread_sub_ln240_1_fu_1175_p2);
    sensitive << ( zext_ln240_1_fu_1149_p1 );

    SC_METHOD(thread_sub_ln240_2_fu_1181_p2);
    sensitive << ( sub_ln240_1_fu_1175_p2 );
    sensitive << ( zext_ln240_5_fu_1171_p1 );

    SC_METHOD(thread_sub_ln240_fu_1157_p2);
    sensitive << ( zext_ln240_fu_1139_p1 );
    sensitive << ( zext_ln240_2_fu_1153_p1 );

    SC_METHOD(thread_sub_ln243_1_fu_1193_p2);
    sensitive << ( zext_ln240_5_fu_1171_p1 );
    sensitive << ( sub_ln243_fu_1187_p2 );

    SC_METHOD(thread_sub_ln243_fu_1187_p2);
    sensitive << ( zext_ln240_1_fu_1149_p1 );

    SC_METHOD(thread_sub_ln254_fu_1376_p2);
    sensitive << ( P_q0 );

    SC_METHOD(thread_sub_ln270_fu_1424_p2);
    sensitive << ( PI_q0 );

    SC_METHOD(thread_tmp_2_fu_892_p3);
    sensitive << ( C_1_fu_180 );

    SC_METHOD(thread_tmp_3_fu_842_p4);
    sensitive << ( C_1_fu_180 );

    SC_METHOD(thread_tmp_4_fu_912_p3);
    sensitive << ( D_fu_184 );

    SC_METHOD(thread_tmp_5_fu_1234_p3);
    sensitive << ( lshr_ln240_1_fu_1224_p2 );

    SC_METHOD(thread_tmp_6_fu_1248_p4);
    sensitive << ( lshr_ln240_1_fu_1224_p2 );

    SC_METHOD(thread_tmp_7_fu_1278_p4);
    sensitive << ( tmp_6_fu_1248_p4 );
    sensitive << ( or_ln241_fu_1242_p2 );

    SC_METHOD(thread_tmp_8_fu_1310_p3);
    sensitive << ( j_2_reg_483 );

    SC_METHOD(thread_tmp_9_fu_952_p3);
    sensitive << ( C_1_fu_180 );
    sensitive << ( D_fu_184 );

    SC_METHOD(thread_tmp_s_fu_864_p4);
    sensitive << ( D_fu_184 );

    SC_METHOD(thread_trunc_ln171_fu_654_p1);
    sensitive << ( lshr_ln174_1_fu_649_p2 );

    SC_METHOD(thread_trunc_ln173_fu_569_p1);
    sensitive << ( init_perm_res_0_0_reg_349 );

    SC_METHOD(thread_trunc_ln174_1_fu_673_p1);
    sensitive << ( lshr_ln174_2_fu_668_p2 );

    SC_METHOD(thread_trunc_ln174_2_fu_692_p1);
    sensitive << ( lshr_ln174_3_fu_687_p2 );

    SC_METHOD(thread_trunc_ln174_fu_635_p1);
    sensitive << ( lshr_ln174_fu_630_p2 );

    SC_METHOD(thread_trunc_ln184_1_fu_726_p1);
    sensitive << ( permuted_choice_1_0_reg_371 );

    SC_METHOD(thread_trunc_ln184_fu_773_p1);
    sensitive << ( lshr_ln184_fu_768_p2 );

    SC_METHOD(thread_trunc_ln197_fu_900_p1);
    sensitive << ( C_1_fu_180 );

    SC_METHOD(thread_trunc_ln198_fu_920_p1);
    sensitive << ( D_fu_184 );

    SC_METHOD(thread_trunc_ln203_fu_838_p1);
    sensitive << ( C_1_fu_180 );

    SC_METHOD(thread_trunc_ln204_fu_860_p1);
    sensitive << ( D_fu_184 );

    SC_METHOD(thread_trunc_ln218_1_fu_977_p1);
    sensitive << ( sub_key_load_1_reg_404 );

    SC_METHOD(thread_trunc_ln218_fu_996_p1);
    sensitive << ( lshr_ln218_fu_991_p2 );

    SC_METHOD(thread_trunc_ln229_1_fu_1075_p1);
    sensitive << ( s_input_0_reg_460 );

    SC_METHOD(thread_trunc_ln229_fu_1071_p1);
    sensitive << ( lshr_ln229_fu_1065_p2 );

    SC_METHOD(thread_trunc_ln232_1_fu_1091_p1);
    sensitive << ( sub_key_q0 );

    SC_METHOD(thread_trunc_ln232_2_fu_1095_p1);
    sensitive << ( s_input_0_reg_460 );

    SC_METHOD(thread_trunc_ln232_3_fu_1099_p1);
    sensitive << ( sub_key_q0 );

    SC_METHOD(thread_trunc_ln232_fu_1087_p1);
    sensitive << ( s_input_0_reg_460 );

    SC_METHOD(thread_trunc_ln240_1_fu_1230_p1);
    sensitive << ( lshr_ln240_1_fu_1224_p2 );

    SC_METHOD(thread_trunc_ln240_fu_1127_p1);
    sensitive << ( j_2_reg_483 );

    SC_METHOD(thread_trunc_ln246_1_fu_1332_p1);
    sensitive << ( s_output_1_fu_188 );

    SC_METHOD(thread_trunc_ln246_fu_1292_p1);
    sensitive << ( lshr_ln243_1_fu_1272_p2 );

    SC_METHOD(thread_trunc_ln254_1_fu_1366_p1);
    sensitive << ( f_function_res_0_reg_495 );

    SC_METHOD(thread_trunc_ln254_fu_1392_p1);
    sensitive << ( lshr_ln254_fu_1386_p2 );

    SC_METHOD(thread_trunc_ln270_1_fu_1420_p1);
    sensitive << ( inv_init_perm_res_0_reg_528 );

    SC_METHOD(thread_trunc_ln270_fu_1439_p1);
    sensitive << ( lshr_ln270_fu_1434_p2 );

    SC_METHOD(thread_xor_ln232_1_fu_1109_p2);
    sensitive << ( trunc_ln232_1_fu_1091_p1 );
    sensitive << ( trunc_ln232_fu_1087_p1 );

    SC_METHOD(thread_xor_ln232_fu_1103_p2);
    sensitive << ( trunc_ln232_3_fu_1099_p1 );
    sensitive << ( trunc_ln232_2_fu_1095_p1 );

    SC_METHOD(thread_zext_ln174_1_fu_645_p1);
    sensitive << ( sub_ln174_1_fu_639_p2 );

    SC_METHOD(thread_zext_ln174_2_fu_664_p1);
    sensitive << ( sub_ln174_2_fu_658_p2 );

    SC_METHOD(thread_zext_ln174_3_fu_683_p1);
    sensitive << ( sub_ln174_3_fu_677_p2 );

    SC_METHOD(thread_zext_ln174_4_fu_626_p1);
    sensitive << ( sub_ln174_fu_620_p2 );

    SC_METHOD(thread_zext_ln174_5_fu_573_p1);
    sensitive << ( or_ln171_fu_563_p2 );

    SC_METHOD(thread_zext_ln174_6_fu_584_p1);
    sensitive << ( or_ln171_1_fu_578_p2 );

    SC_METHOD(thread_zext_ln174_7_fu_595_p1);
    sensitive << ( or_ln171_2_fu_589_p2 );

    SC_METHOD(thread_zext_ln174_fu_554_p1);
    sensitive << ( i_0_0_reg_360 );

    SC_METHOD(thread_zext_ln184_1_fu_721_p1);
    sensitive << ( i_1_reg_382 );

    SC_METHOD(thread_zext_ln184_2_fu_754_p1);
    sensitive << ( PC1_q0 );

    SC_METHOD(thread_zext_ln184_fu_764_p1);
    sensitive << ( sub_ln184_fu_758_p2 );

    SC_METHOD(thread_zext_ln214_fu_942_p1);
    sensitive << ( i_2_reg_393 );

    SC_METHOD(thread_zext_ln218_1_fu_987_p1);
    sensitive << ( sub_ln218_fu_981_p2 );

    SC_METHOD(thread_zext_ln218_fu_972_p1);
    sensitive << ( j_0_reg_416 );

    SC_METHOD(thread_zext_ln229_1_fu_1061_p1);
    sensitive << ( sub_ln229_fu_1055_p2 );

    SC_METHOD(thread_zext_ln229_fu_1039_p1);
    sensitive << ( j_1_reg_472 );

    SC_METHOD(thread_zext_ln232_fu_1050_p1);
    sensitive << ( sub_ln232_fu_1044_p2 );

    SC_METHOD(thread_zext_ln240_1_fu_1149_p1);
    sensitive << ( shl_ln240_fu_1143_p2 );

    SC_METHOD(thread_zext_ln240_2_fu_1153_p1);
    sensitive << ( shl_ln240_fu_1143_p2 );

    SC_METHOD(thread_zext_ln240_3_fu_1202_p1);
    sensitive << ( sext_ln240_fu_1199_p1 );

    SC_METHOD(thread_zext_ln240_4_fu_1206_p1);
    sensitive << ( sext_ln240_fu_1199_p1 );

    SC_METHOD(thread_zext_ln240_5_fu_1171_p1);
    sensitive << ( shl_ln240_1_fu_1163_p3 );

    SC_METHOD(thread_zext_ln240_6_fu_1221_p1);
    sensitive << ( sub_ln240_2_reg_1660 );

    SC_METHOD(thread_zext_ln240_fu_1139_p1);
    sensitive << ( shl_ln_fu_1131_p3 );

    SC_METHOD(thread_zext_ln243_fu_1269_p1);
    sensitive << ( sub_ln243_1_reg_1665 );

    SC_METHOD(thread_zext_ln246_fu_1318_p1);
    sensitive << ( tmp_8_fu_1310_p3 );

    SC_METHOD(thread_zext_ln254_1_fu_1382_p1);
    sensitive << ( sub_ln254_fu_1376_p2 );

    SC_METHOD(thread_zext_ln254_fu_1361_p1);
    sensitive << ( j_3_reg_506 );

    SC_METHOD(thread_zext_ln270_1_fu_1415_p1);
    sensitive << ( i_4_reg_517 );

    SC_METHOD(thread_zext_ln270_fu_1430_p1);
    sensitive << ( sub_ln270_fu_1424_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln171_fu_548_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln182_fu_709_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln192_fu_784_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln216_fu_960_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln223_fu_1007_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln227_fu_1027_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln235_fu_1115_p2 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln252_fu_1349_p2 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( icmp_ln267_fu_1403_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "des_dec_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r, "(port)input_r");
    sc_trace(mVcdFile, key, "(port)key");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, IP_address0, "IP_address0");
    sc_trace(mVcdFile, IP_ce0, "IP_ce0");
    sc_trace(mVcdFile, IP_q0, "IP_q0");
    sc_trace(mVcdFile, IP_address1, "IP_address1");
    sc_trace(mVcdFile, IP_ce1, "IP_ce1");
    sc_trace(mVcdFile, IP_q1, "IP_q1");
    sc_trace(mVcdFile, IP_address2, "IP_address2");
    sc_trace(mVcdFile, IP_ce2, "IP_ce2");
    sc_trace(mVcdFile, IP_q2, "IP_q2");
    sc_trace(mVcdFile, IP_address3, "IP_address3");
    sc_trace(mVcdFile, IP_ce3, "IP_ce3");
    sc_trace(mVcdFile, IP_q3, "IP_q3");
    sc_trace(mVcdFile, PC1_address0, "PC1_address0");
    sc_trace(mVcdFile, PC1_ce0, "PC1_ce0");
    sc_trace(mVcdFile, PC1_q0, "PC1_q0");
    sc_trace(mVcdFile, PC2_address0, "PC2_address0");
    sc_trace(mVcdFile, PC2_ce0, "PC2_ce0");
    sc_trace(mVcdFile, PC2_q0, "PC2_q0");
    sc_trace(mVcdFile, E_address0, "E_address0");
    sc_trace(mVcdFile, E_ce0, "E_ce0");
    sc_trace(mVcdFile, E_q0, "E_q0");
    sc_trace(mVcdFile, S_address0, "S_address0");
    sc_trace(mVcdFile, S_ce0, "S_ce0");
    sc_trace(mVcdFile, S_q0, "S_q0");
    sc_trace(mVcdFile, P_address0, "P_address0");
    sc_trace(mVcdFile, P_ce0, "P_ce0");
    sc_trace(mVcdFile, P_q0, "P_q0");
    sc_trace(mVcdFile, PI_address0, "PI_address0");
    sc_trace(mVcdFile, PI_ce0, "PI_ce0");
    sc_trace(mVcdFile, PI_q0, "PI_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln171_fu_548_p2, "icmp_ln171_fu_548_p2");
    sc_trace(mVcdFile, trunc_ln173_fu_569_p1, "trunc_ln173_fu_569_p1");
    sc_trace(mVcdFile, trunc_ln173_reg_1471, "trunc_ln173_reg_1471");
    sc_trace(mVcdFile, add_ln171_fu_600_p2, "add_ln171_fu_600_p2");
    sc_trace(mVcdFile, add_ln171_reg_1491, "add_ln171_reg_1491");
    sc_trace(mVcdFile, L_reg_1496, "L_reg_1496");
    sc_trace(mVcdFile, R_fu_616_p1, "R_fu_616_p1");
    sc_trace(mVcdFile, R_reg_1501, "R_reg_1501");
    sc_trace(mVcdFile, or_ln_fu_696_p6, "or_ln_fu_696_p6");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_715_p2, "i_fu_715_p2");
    sc_trace(mVcdFile, i_reg_1514, "i_reg_1514");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln182_fu_709_p2, "icmp_ln182_fu_709_p2");
    sc_trace(mVcdFile, trunc_ln184_1_fu_726_p1, "trunc_ln184_1_fu_726_p1");
    sc_trace(mVcdFile, trunc_ln184_1_reg_1524, "trunc_ln184_1_reg_1524");
    sc_trace(mVcdFile, permuted_choice_1_fu_777_p3, "permuted_choice_1_fu_777_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_6_fu_790_p2, "i_6_fu_790_p2");
    sc_trace(mVcdFile, i_6_reg_1553, "i_6_reg_1553");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, sub_key_addr_reg_1561, "sub_key_addr_reg_1561");
    sc_trace(mVcdFile, icmp_ln192_fu_784_p2, "icmp_ln192_fu_784_p2");
    sc_trace(mVcdFile, tmp_9_fu_952_p3, "tmp_9_fu_952_p3");
    sc_trace(mVcdFile, tmp_9_reg_1573, "tmp_9_reg_1573");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, j_4_fu_966_p2, "j_4_fu_966_p2");
    sc_trace(mVcdFile, j_4_reg_1581, "j_4_reg_1581");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln216_fu_960_p2, "icmp_ln216_fu_960_p2");
    sc_trace(mVcdFile, trunc_ln218_1_fu_977_p1, "trunc_ln218_1_fu_977_p1");
    sc_trace(mVcdFile, trunc_ln218_1_reg_1591, "trunc_ln218_1_reg_1591");
    sc_trace(mVcdFile, or_ln1_fu_1000_p3, "or_ln1_fu_1000_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_7_fu_1013_p2, "i_7_fu_1013_p2");
    sc_trace(mVcdFile, i_7_reg_1604, "i_7_reg_1604");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, pre_output_fu_1019_p3, "pre_output_fu_1019_p3");
    sc_trace(mVcdFile, pre_output_reg_1609, "pre_output_reg_1609");
    sc_trace(mVcdFile, icmp_ln223_fu_1007_p2, "icmp_ln223_fu_1007_p2");
    sc_trace(mVcdFile, j_fu_1033_p2, "j_fu_1033_p2");
    sc_trace(mVcdFile, j_reg_1617, "j_reg_1617");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, icmp_ln227_fu_1027_p2, "icmp_ln227_fu_1027_p2");
    sc_trace(mVcdFile, s_input_fu_1079_p3, "s_input_fu_1079_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, xor_ln232_fu_1103_p2, "xor_ln232_fu_1103_p2");
    sc_trace(mVcdFile, xor_ln232_reg_1637, "xor_ln232_reg_1637");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, xor_ln232_1_fu_1109_p2, "xor_ln232_1_fu_1109_p2");
    sc_trace(mVcdFile, xor_ln232_1_reg_1642, "xor_ln232_1_reg_1642");
    sc_trace(mVcdFile, j_5_fu_1121_p2, "j_5_fu_1121_p2");
    sc_trace(mVcdFile, j_5_reg_1650, "j_5_reg_1650");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, sub_ln240_fu_1157_p2, "sub_ln240_fu_1157_p2");
    sc_trace(mVcdFile, sub_ln240_reg_1655, "sub_ln240_reg_1655");
    sc_trace(mVcdFile, icmp_ln235_fu_1115_p2, "icmp_ln235_fu_1115_p2");
    sc_trace(mVcdFile, sub_ln240_2_fu_1181_p2, "sub_ln240_2_fu_1181_p2");
    sc_trace(mVcdFile, sub_ln240_2_reg_1660, "sub_ln240_2_reg_1660");
    sc_trace(mVcdFile, sub_ln243_1_fu_1193_p2, "sub_ln243_1_fu_1193_p2");
    sc_trace(mVcdFile, sub_ln243_1_reg_1665, "sub_ln243_1_reg_1665");
    sc_trace(mVcdFile, add_ln246_1_fu_1322_p2, "add_ln246_1_fu_1322_p2");
    sc_trace(mVcdFile, add_ln246_1_reg_1670, "add_ln246_1_reg_1670");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, j_6_fu_1355_p2, "j_6_fu_1355_p2");
    sc_trace(mVcdFile, j_6_reg_1683, "j_6_reg_1683");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, icmp_ln252_fu_1349_p2, "icmp_ln252_fu_1349_p2");
    sc_trace(mVcdFile, trunc_ln254_1_fu_1366_p1, "trunc_ln254_1_fu_1366_p1");
    sc_trace(mVcdFile, trunc_ln254_1_reg_1693, "trunc_ln254_1_reg_1693");
    sc_trace(mVcdFile, R_1_fu_1370_p2, "R_1_fu_1370_p2");
    sc_trace(mVcdFile, f_function_res_fu_1396_p3, "f_function_res_fu_1396_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, i_5_fu_1409_p2, "i_5_fu_1409_p2");
    sc_trace(mVcdFile, i_5_reg_1711, "i_5_reg_1711");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, icmp_ln267_fu_1403_p2, "icmp_ln267_fu_1403_p2");
    sc_trace(mVcdFile, trunc_ln270_1_fu_1420_p1, "trunc_ln270_1_fu_1420_p1");
    sc_trace(mVcdFile, trunc_ln270_1_reg_1721, "trunc_ln270_1_reg_1721");
    sc_trace(mVcdFile, inv_init_perm_res_fu_1443_p3, "inv_init_perm_res_fu_1443_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, sub_key_address0, "sub_key_address0");
    sc_trace(mVcdFile, sub_key_ce0, "sub_key_ce0");
    sc_trace(mVcdFile, sub_key_we0, "sub_key_we0");
    sc_trace(mVcdFile, sub_key_q0, "sub_key_q0");
    sc_trace(mVcdFile, init_perm_res_0_0_reg_349, "init_perm_res_0_0_reg_349");
    sc_trace(mVcdFile, i_0_0_reg_360, "i_0_0_reg_360");
    sc_trace(mVcdFile, permuted_choice_1_0_reg_371, "permuted_choice_1_0_reg_371");
    sc_trace(mVcdFile, i_1_reg_382, "i_1_reg_382");
    sc_trace(mVcdFile, i_2_reg_393, "i_2_reg_393");
    sc_trace(mVcdFile, sub_key_load_1_reg_404, "sub_key_load_1_reg_404");
    sc_trace(mVcdFile, j_0_reg_416, "j_0_reg_416");
    sc_trace(mVcdFile, temp_reg_427, "temp_reg_427");
    sc_trace(mVcdFile, L_0_reg_437, "L_0_reg_437");
    sc_trace(mVcdFile, i_3_reg_448, "i_3_reg_448");
    sc_trace(mVcdFile, s_input_0_reg_460, "s_input_0_reg_460");
    sc_trace(mVcdFile, j_1_reg_472, "j_1_reg_472");
    sc_trace(mVcdFile, j_2_reg_483, "j_2_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, f_function_res_0_reg_495, "f_function_res_0_reg_495");
    sc_trace(mVcdFile, j_3_reg_506, "j_3_reg_506");
    sc_trace(mVcdFile, i_4_reg_517, "i_4_reg_517");
    sc_trace(mVcdFile, inv_init_perm_res_0_reg_528, "inv_init_perm_res_0_reg_528");
    sc_trace(mVcdFile, zext_ln174_fu_554_p1, "zext_ln174_fu_554_p1");
    sc_trace(mVcdFile, zext_ln174_5_fu_573_p1, "zext_ln174_5_fu_573_p1");
    sc_trace(mVcdFile, zext_ln174_6_fu_584_p1, "zext_ln174_6_fu_584_p1");
    sc_trace(mVcdFile, zext_ln174_7_fu_595_p1, "zext_ln174_7_fu_595_p1");
    sc_trace(mVcdFile, zext_ln184_1_fu_721_p1, "zext_ln184_1_fu_721_p1");
    sc_trace(mVcdFile, zext_ln214_fu_942_p1, "zext_ln214_fu_942_p1");
    sc_trace(mVcdFile, zext_ln218_fu_972_p1, "zext_ln218_fu_972_p1");
    sc_trace(mVcdFile, zext_ln229_fu_1039_p1, "zext_ln229_fu_1039_p1");
    sc_trace(mVcdFile, zext_ln232_fu_1050_p1, "zext_ln232_fu_1050_p1");
    sc_trace(mVcdFile, sext_ln246_3_fu_1328_p1, "sext_ln246_3_fu_1328_p1");
    sc_trace(mVcdFile, zext_ln254_fu_1361_p1, "zext_ln254_fu_1361_p1");
    sc_trace(mVcdFile, zext_ln270_1_fu_1415_p1, "zext_ln270_1_fu_1415_p1");
    sc_trace(mVcdFile, C_1_fu_180, "C_1_fu_180");
    sc_trace(mVcdFile, C_2_fu_852_p3, "C_2_fu_852_p3");
    sc_trace(mVcdFile, empty_18_fu_832_p2, "empty_18_fu_832_p2");
    sc_trace(mVcdFile, C_3_fu_904_p3, "C_3_fu_904_p3");
    sc_trace(mVcdFile, D_fu_184, "D_fu_184");
    sc_trace(mVcdFile, D_1_fu_740_p1, "D_1_fu_740_p1");
    sc_trace(mVcdFile, D_2_fu_874_p3, "D_2_fu_874_p3");
    sc_trace(mVcdFile, D_3_fu_924_p3, "D_3_fu_924_p3");
    sc_trace(mVcdFile, s_output_1_fu_188, "s_output_1_fu_188");
    sc_trace(mVcdFile, s_output_fu_1336_p3, "s_output_fu_1336_p3");
    sc_trace(mVcdFile, empty_9_fu_559_p1, "empty_9_fu_559_p1");
    sc_trace(mVcdFile, or_ln171_fu_563_p2, "or_ln171_fu_563_p2");
    sc_trace(mVcdFile, or_ln171_1_fu_578_p2, "or_ln171_1_fu_578_p2");
    sc_trace(mVcdFile, or_ln171_2_fu_589_p2, "or_ln171_2_fu_589_p2");
    sc_trace(mVcdFile, sub_ln174_fu_620_p2, "sub_ln174_fu_620_p2");
    sc_trace(mVcdFile, zext_ln174_4_fu_626_p1, "zext_ln174_4_fu_626_p1");
    sc_trace(mVcdFile, lshr_ln174_fu_630_p2, "lshr_ln174_fu_630_p2");
    sc_trace(mVcdFile, sub_ln174_1_fu_639_p2, "sub_ln174_1_fu_639_p2");
    sc_trace(mVcdFile, zext_ln174_1_fu_645_p1, "zext_ln174_1_fu_645_p1");
    sc_trace(mVcdFile, lshr_ln174_1_fu_649_p2, "lshr_ln174_1_fu_649_p2");
    sc_trace(mVcdFile, sub_ln174_2_fu_658_p2, "sub_ln174_2_fu_658_p2");
    sc_trace(mVcdFile, zext_ln174_2_fu_664_p1, "zext_ln174_2_fu_664_p1");
    sc_trace(mVcdFile, lshr_ln174_2_fu_668_p2, "lshr_ln174_2_fu_668_p2");
    sc_trace(mVcdFile, sub_ln174_3_fu_677_p2, "sub_ln174_3_fu_677_p2");
    sc_trace(mVcdFile, zext_ln174_3_fu_683_p1, "zext_ln174_3_fu_683_p1");
    sc_trace(mVcdFile, lshr_ln174_3_fu_687_p2, "lshr_ln174_3_fu_687_p2");
    sc_trace(mVcdFile, trunc_ln174_fu_635_p1, "trunc_ln174_fu_635_p1");
    sc_trace(mVcdFile, trunc_ln171_fu_654_p1, "trunc_ln171_fu_654_p1");
    sc_trace(mVcdFile, trunc_ln174_1_fu_673_p1, "trunc_ln174_1_fu_673_p1");
    sc_trace(mVcdFile, trunc_ln174_2_fu_692_p1, "trunc_ln174_2_fu_692_p1");
    sc_trace(mVcdFile, zext_ln184_2_fu_754_p1, "zext_ln184_2_fu_754_p1");
    sc_trace(mVcdFile, sub_ln184_fu_758_p2, "sub_ln184_fu_758_p2");
    sc_trace(mVcdFile, zext_ln184_fu_764_p1, "zext_ln184_fu_764_p1");
    sc_trace(mVcdFile, lshr_ln184_fu_768_p2, "lshr_ln184_fu_768_p2");
    sc_trace(mVcdFile, trunc_ln184_fu_773_p1, "trunc_ln184_fu_773_p1");
    sc_trace(mVcdFile, empty_13_fu_802_p2, "empty_13_fu_802_p2");
    sc_trace(mVcdFile, empty_12_fu_796_p2, "empty_12_fu_796_p2");
    sc_trace(mVcdFile, empty_15_fu_814_p2, "empty_15_fu_814_p2");
    sc_trace(mVcdFile, empty_14_fu_808_p2, "empty_14_fu_808_p2");
    sc_trace(mVcdFile, empty_17_fu_826_p2, "empty_17_fu_826_p2");
    sc_trace(mVcdFile, empty_16_fu_820_p2, "empty_16_fu_820_p2");
    sc_trace(mVcdFile, trunc_ln203_fu_838_p1, "trunc_ln203_fu_838_p1");
    sc_trace(mVcdFile, tmp_3_fu_842_p4, "tmp_3_fu_842_p4");
    sc_trace(mVcdFile, trunc_ln204_fu_860_p1, "trunc_ln204_fu_860_p1");
    sc_trace(mVcdFile, tmp_s_fu_864_p4, "tmp_s_fu_864_p4");
    sc_trace(mVcdFile, trunc_ln197_fu_900_p1, "trunc_ln197_fu_900_p1");
    sc_trace(mVcdFile, tmp_2_fu_892_p3, "tmp_2_fu_892_p3");
    sc_trace(mVcdFile, trunc_ln198_fu_920_p1, "trunc_ln198_fu_920_p1");
    sc_trace(mVcdFile, tmp_4_fu_912_p3, "tmp_4_fu_912_p3");
    sc_trace(mVcdFile, sub_ln218_fu_981_p2, "sub_ln218_fu_981_p2");
    sc_trace(mVcdFile, zext_ln218_1_fu_987_p1, "zext_ln218_1_fu_987_p1");
    sc_trace(mVcdFile, lshr_ln218_fu_991_p2, "lshr_ln218_fu_991_p2");
    sc_trace(mVcdFile, trunc_ln218_fu_996_p1, "trunc_ln218_fu_996_p1");
    sc_trace(mVcdFile, sub_ln232_fu_1044_p2, "sub_ln232_fu_1044_p2");
    sc_trace(mVcdFile, sub_ln229_fu_1055_p2, "sub_ln229_fu_1055_p2");
    sc_trace(mVcdFile, zext_ln229_1_fu_1061_p1, "zext_ln229_1_fu_1061_p1");
    sc_trace(mVcdFile, lshr_ln229_fu_1065_p2, "lshr_ln229_fu_1065_p2");
    sc_trace(mVcdFile, trunc_ln229_1_fu_1075_p1, "trunc_ln229_1_fu_1075_p1");
    sc_trace(mVcdFile, trunc_ln229_fu_1071_p1, "trunc_ln229_fu_1071_p1");
    sc_trace(mVcdFile, trunc_ln232_3_fu_1099_p1, "trunc_ln232_3_fu_1099_p1");
    sc_trace(mVcdFile, trunc_ln232_2_fu_1095_p1, "trunc_ln232_2_fu_1095_p1");
    sc_trace(mVcdFile, trunc_ln232_1_fu_1091_p1, "trunc_ln232_1_fu_1091_p1");
    sc_trace(mVcdFile, trunc_ln232_fu_1087_p1, "trunc_ln232_fu_1087_p1");
    sc_trace(mVcdFile, trunc_ln240_fu_1127_p1, "trunc_ln240_fu_1127_p1");
    sc_trace(mVcdFile, shl_ln_fu_1131_p3, "shl_ln_fu_1131_p3");
    sc_trace(mVcdFile, shl_ln240_fu_1143_p2, "shl_ln240_fu_1143_p2");
    sc_trace(mVcdFile, zext_ln240_fu_1139_p1, "zext_ln240_fu_1139_p1");
    sc_trace(mVcdFile, zext_ln240_2_fu_1153_p1, "zext_ln240_2_fu_1153_p1");
    sc_trace(mVcdFile, shl_ln240_1_fu_1163_p3, "shl_ln240_1_fu_1163_p3");
    sc_trace(mVcdFile, zext_ln240_1_fu_1149_p1, "zext_ln240_1_fu_1149_p1");
    sc_trace(mVcdFile, sub_ln240_1_fu_1175_p2, "sub_ln240_1_fu_1175_p2");
    sc_trace(mVcdFile, zext_ln240_5_fu_1171_p1, "zext_ln240_5_fu_1171_p1");
    sc_trace(mVcdFile, sub_ln243_fu_1187_p2, "sub_ln243_fu_1187_p2");
    sc_trace(mVcdFile, sext_ln240_fu_1199_p1, "sext_ln240_fu_1199_p1");
    sc_trace(mVcdFile, zext_ln240_4_fu_1206_p1, "zext_ln240_4_fu_1206_p1");
    sc_trace(mVcdFile, lshr_ln240_fu_1210_p2, "lshr_ln240_fu_1210_p2");
    sc_trace(mVcdFile, and_ln240_fu_1216_p2, "and_ln240_fu_1216_p2");
    sc_trace(mVcdFile, zext_ln240_6_fu_1221_p1, "zext_ln240_6_fu_1221_p1");
    sc_trace(mVcdFile, lshr_ln240_1_fu_1224_p2, "lshr_ln240_1_fu_1224_p2");
    sc_trace(mVcdFile, tmp_5_fu_1234_p3, "tmp_5_fu_1234_p3");
    sc_trace(mVcdFile, trunc_ln240_1_fu_1230_p1, "trunc_ln240_1_fu_1230_p1");
    sc_trace(mVcdFile, zext_ln240_3_fu_1202_p1, "zext_ln240_3_fu_1202_p1");
    sc_trace(mVcdFile, lshr_ln243_fu_1258_p2, "lshr_ln243_fu_1258_p2");
    sc_trace(mVcdFile, and_ln243_fu_1264_p2, "and_ln243_fu_1264_p2");
    sc_trace(mVcdFile, zext_ln243_fu_1269_p1, "zext_ln243_fu_1269_p1");
    sc_trace(mVcdFile, tmp_6_fu_1248_p4, "tmp_6_fu_1248_p4");
    sc_trace(mVcdFile, or_ln241_fu_1242_p2, "or_ln241_fu_1242_p2");
    sc_trace(mVcdFile, tmp_7_fu_1278_p4, "tmp_7_fu_1278_p4");
    sc_trace(mVcdFile, lshr_ln243_1_fu_1272_p2, "lshr_ln243_1_fu_1272_p2");
    sc_trace(mVcdFile, trunc_ln246_fu_1292_p1, "trunc_ln246_fu_1292_p1");
    sc_trace(mVcdFile, sext_ln246_1_fu_1296_p1, "sext_ln246_1_fu_1296_p1");
    sc_trace(mVcdFile, sext_ln246_fu_1288_p1, "sext_ln246_fu_1288_p1");
    sc_trace(mVcdFile, add_ln246_fu_1300_p2, "add_ln246_fu_1300_p2");
    sc_trace(mVcdFile, tmp_8_fu_1310_p3, "tmp_8_fu_1310_p3");
    sc_trace(mVcdFile, sext_ln246_2_fu_1306_p1, "sext_ln246_2_fu_1306_p1");
    sc_trace(mVcdFile, zext_ln246_fu_1318_p1, "zext_ln246_fu_1318_p1");
    sc_trace(mVcdFile, trunc_ln246_1_fu_1332_p1, "trunc_ln246_1_fu_1332_p1");
    sc_trace(mVcdFile, sub_ln254_fu_1376_p2, "sub_ln254_fu_1376_p2");
    sc_trace(mVcdFile, zext_ln254_1_fu_1382_p1, "zext_ln254_1_fu_1382_p1");
    sc_trace(mVcdFile, lshr_ln254_fu_1386_p2, "lshr_ln254_fu_1386_p2");
    sc_trace(mVcdFile, trunc_ln254_fu_1392_p1, "trunc_ln254_fu_1392_p1");
    sc_trace(mVcdFile, sub_ln270_fu_1424_p2, "sub_ln270_fu_1424_p2");
    sc_trace(mVcdFile, zext_ln270_fu_1430_p1, "zext_ln270_fu_1430_p1");
    sc_trace(mVcdFile, lshr_ln270_fu_1434_p2, "lshr_ln270_fu_1434_p2");
    sc_trace(mVcdFile, trunc_ln270_fu_1439_p1, "trunc_ln270_fu_1439_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("des_dec.hdltvin.dat");
    mHdltvoutHandle.open("des_dec.hdltvout.dat");
}

des_dec::~des_dec() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete IP_U;
    delete PC1_U;
    delete PC2_U;
    delete E_U;
    delete S_U;
    delete P_U;
    delete PI_U;
    delete sub_key_U;
}

void des_dec::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln192_fu_784_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, empty_18_fu_832_p2.read()))) {
        C_1_fu_180 = C_3_fu_904_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln192_fu_784_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, empty_18_fu_832_p2.read()))) {
        C_1_fu_180 = C_2_fu_852_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln182_fu_709_p2.read()))) {
        C_1_fu_180 = permuted_choice_1_0_reg_371.read().range(55, 28);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln192_fu_784_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, empty_18_fu_832_p2.read()))) {
        D_fu_184 = D_3_fu_924_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln192_fu_784_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, empty_18_fu_832_p2.read()))) {
        D_fu_184 = D_2_fu_874_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln182_fu_709_p2.read()))) {
        D_fu_184 = D_1_fu_740_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln192_fu_784_p2.read()))) {
        L_0_reg_437 = L_reg_1496.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln252_fu_1349_p2.read()))) {
        L_0_reg_437 = temp_reg_427.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln235_fu_1115_p2.read()))) {
        f_function_res_0_reg_495 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        f_function_res_0_reg_495 = f_function_res_fu_1396_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_0_reg_360 = add_ln171_reg_1491.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_0_reg_360 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_1_reg_382 = i_reg_1514.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_548_p2.read(), ap_const_lv1_1))) {
        i_1_reg_382 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln216_fu_960_p2.read()))) {
        i_2_reg_393 = i_6_reg_1553.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln182_fu_709_p2.read()))) {
        i_2_reg_393 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln192_fu_784_p2.read()))) {
        i_3_reg_448 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln252_fu_1349_p2.read()))) {
        i_3_reg_448 = i_7_reg_1604.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i_4_reg_517 = i_5_reg_1711.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln223_fu_1007_p2.read()))) {
        i_4_reg_517 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        init_perm_res_0_0_reg_349 = or_ln_fu_696_p6.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        init_perm_res_0_0_reg_349 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        inv_init_perm_res_0_reg_528 = inv_init_perm_res_fu_1443_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln223_fu_1007_p2.read()))) {
        inv_init_perm_res_0_reg_528 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        j_0_reg_416 = j_4_reg_1581.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_0_reg_416 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j_1_reg_472 = j_reg_1617.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln223_fu_1007_p2.read()))) {
        j_1_reg_472 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        j_2_reg_483 = j_5_reg_1650.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_2_reg_483 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln235_fu_1115_p2.read()))) {
        j_3_reg_506 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        j_3_reg_506 = j_6_reg_1683.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        permuted_choice_1_0_reg_371 = permuted_choice_1_fu_777_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln171_fu_548_p2.read(), ap_const_lv1_1))) {
        permuted_choice_1_0_reg_371 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        s_input_0_reg_460 = s_input_fu_1079_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln223_fu_1007_p2.read()))) {
        s_input_0_reg_460 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        s_output_1_fu_188 = s_output_fu_1336_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln192_fu_784_p2.read()))) {
        s_output_1_fu_188 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sub_key_load_1_reg_404 = or_ln1_fu_1000_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sub_key_load_1_reg_404 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln192_fu_784_p2.read()))) {
        temp_reg_427 = R_reg_1501.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln252_fu_1349_p2.read()))) {
        temp_reg_427 = R_1_fu_1370_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_548_p2.read(), ap_const_lv1_1))) {
        L_reg_1496 = init_perm_res_0_0_reg_349.read().range(63, 32);
        R_reg_1501 = R_fu_616_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_548_p2.read(), ap_const_lv1_0))) {
        add_ln171_reg_1491 = add_ln171_fu_600_p2.read();
        trunc_ln173_reg_1471 = trunc_ln173_fu_569_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        add_ln246_1_reg_1670 = add_ln246_1_fu_1322_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i_5_reg_1711 = i_5_fu_1409_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_6_reg_1553 = i_6_fu_790_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_7_reg_1604 = i_7_fu_1013_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_1514 = i_fu_715_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_4_reg_1581 = j_4_fu_966_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        j_5_reg_1650 = j_5_fu_1121_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        j_6_reg_1683 = j_6_fu_1355_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        j_reg_1617 = j_fu_1033_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln223_fu_1007_p2.read()))) {
        pre_output_reg_1609 = pre_output_fu_1019_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln192_fu_784_p2.read()))) {
        sub_key_addr_reg_1561 =  (sc_lv<4>) (zext_ln214_fu_942_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln235_fu_1115_p2.read()))) {
        sub_ln240_2_reg_1660 = sub_ln240_2_fu_1181_p2.read();
        sub_ln240_reg_1655 = sub_ln240_fu_1157_p2.read();
        sub_ln243_1_reg_1665 = sub_ln243_1_fu_1193_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_9_reg_1573 = tmp_9_fu_952_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln182_fu_709_p2.read()))) {
        trunc_ln184_1_reg_1524 = trunc_ln184_1_fu_726_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln216_fu_960_p2.read()))) {
        trunc_ln218_1_reg_1591 = trunc_ln218_1_fu_977_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln252_fu_1349_p2.read()))) {
        trunc_ln254_1_reg_1693 = trunc_ln254_1_fu_1366_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln267_fu_1403_p2.read()))) {
        trunc_ln270_1_reg_1721 = trunc_ln270_1_fu_1420_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        xor_ln232_1_reg_1642 = xor_ln232_1_fu_1109_p2.read();
        xor_ln232_reg_1637 = xor_ln232_fu_1103_p2.read();
    }
}

void des_dec::thread_C_2_fu_852_p3() {
    C_2_fu_852_p3 = esl_concat<26,2>(trunc_ln203_fu_838_p1.read(), tmp_3_fu_842_p4.read());
}

void des_dec::thread_C_3_fu_904_p3() {
    C_3_fu_904_p3 = esl_concat<27,1>(trunc_ln197_fu_900_p1.read(), tmp_2_fu_892_p3.read());
}

void des_dec::thread_D_1_fu_740_p1() {
    D_1_fu_740_p1 = permuted_choice_1_0_reg_371.read().range(28-1, 0);
}

void des_dec::thread_D_2_fu_874_p3() {
    D_2_fu_874_p3 = esl_concat<26,2>(trunc_ln204_fu_860_p1.read(), tmp_s_fu_864_p4.read());
}

void des_dec::thread_D_3_fu_924_p3() {
    D_3_fu_924_p3 = esl_concat<27,1>(trunc_ln198_fu_920_p1.read(), tmp_4_fu_912_p3.read());
}

void des_dec::thread_E_address0() {
    E_address0 =  (sc_lv<6>) (zext_ln229_fu_1039_p1.read());
}

void des_dec::thread_E_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        E_ce0 = ap_const_logic_1;
    } else {
        E_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_IP_address0() {
    IP_address0 =  (sc_lv<6>) (zext_ln174_fu_554_p1.read());
}

void des_dec::thread_IP_address1() {
    IP_address1 =  (sc_lv<6>) (zext_ln174_5_fu_573_p1.read());
}

void des_dec::thread_IP_address2() {
    IP_address2 =  (sc_lv<6>) (zext_ln174_6_fu_584_p1.read());
}

void des_dec::thread_IP_address3() {
    IP_address3 =  (sc_lv<6>) (zext_ln174_7_fu_595_p1.read());
}

void des_dec::thread_IP_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IP_ce0 = ap_const_logic_1;
    } else {
        IP_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_IP_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IP_ce1 = ap_const_logic_1;
    } else {
        IP_ce1 = ap_const_logic_0;
    }
}

void des_dec::thread_IP_ce2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IP_ce2 = ap_const_logic_1;
    } else {
        IP_ce2 = ap_const_logic_0;
    }
}

void des_dec::thread_IP_ce3() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        IP_ce3 = ap_const_logic_1;
    } else {
        IP_ce3 = ap_const_logic_0;
    }
}

void des_dec::thread_PC1_address0() {
    PC1_address0 =  (sc_lv<6>) (zext_ln184_1_fu_721_p1.read());
}

void des_dec::thread_PC1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        PC1_ce0 = ap_const_logic_1;
    } else {
        PC1_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_PC2_address0() {
    PC2_address0 =  (sc_lv<6>) (zext_ln218_fu_972_p1.read());
}

void des_dec::thread_PC2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        PC2_ce0 = ap_const_logic_1;
    } else {
        PC2_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_PI_address0() {
    PI_address0 =  (sc_lv<6>) (zext_ln270_1_fu_1415_p1.read());
}

void des_dec::thread_PI_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        PI_ce0 = ap_const_logic_1;
    } else {
        PI_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_P_address0() {
    P_address0 =  (sc_lv<5>) (zext_ln254_fu_1361_p1.read());
}

void des_dec::thread_P_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        P_ce0 = ap_const_logic_1;
    } else {
        P_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_R_1_fu_1370_p2() {
    R_1_fu_1370_p2 = (f_function_res_0_reg_495.read() ^ L_0_reg_437.read());
}

void des_dec::thread_R_fu_616_p1() {
    R_fu_616_p1 = init_perm_res_0_0_reg_349.read().range(32-1, 0);
}

void des_dec::thread_S_address0() {
    S_address0 =  (sc_lv<9>) (sext_ln246_3_fu_1328_p1.read());
}

void des_dec::thread_S_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        S_ce0 = ap_const_logic_1;
    } else {
        S_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_add_ln171_fu_600_p2() {
    add_ln171_fu_600_p2 = (!ap_const_lv7_4.is_01() || !i_0_0_reg_360.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_4) + sc_biguint<7>(i_0_0_reg_360.read()));
}

void des_dec::thread_add_ln246_1_fu_1322_p2() {
    add_ln246_1_fu_1322_p2 = (!sext_ln246_2_fu_1306_p1.read().is_01() || !zext_ln246_fu_1318_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(sext_ln246_2_fu_1306_p1.read()) + sc_biguint<11>(zext_ln246_fu_1318_p1.read()));
}

void des_dec::thread_add_ln246_fu_1300_p2() {
    add_ln246_fu_1300_p2 = (!sext_ln246_1_fu_1296_p1.read().is_01() || !sext_ln246_fu_1288_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln246_1_fu_1296_p1.read()) + sc_bigint<9>(sext_ln246_fu_1288_p1.read()));
}

void des_dec::thread_and_ln240_fu_1216_p2() {
    and_ln240_fu_1216_p2 = (lshr_ln240_fu_1210_p2.read() & xor_ln232_1_reg_1642.read());
}

void des_dec::thread_and_ln243_fu_1264_p2() {
    and_ln243_fu_1264_p2 = (lshr_ln243_fu_1258_p2.read() & xor_ln232_reg_1637.read());
}

void des_dec::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void des_dec::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void des_dec::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void des_dec::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void des_dec::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void des_dec::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void des_dec::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void des_dec::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void des_dec::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void des_dec::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void des_dec::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void des_dec::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void des_dec::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void des_dec::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void des_dec::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void des_dec::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void des_dec::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void des_dec::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void des_dec::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void des_dec::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void des_dec::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void des_dec::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln267_fu_1403_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void des_dec::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void des_dec::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln267_fu_1403_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void des_dec::thread_ap_return() {
    ap_return = inv_init_perm_res_0_reg_528.read();
}

void des_dec::thread_empty_12_fu_796_p2() {
    empty_12_fu_796_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_F.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_393.read() == ap_const_lv5_F);
}

void des_dec::thread_empty_13_fu_802_p2() {
    empty_13_fu_802_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_8.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_393.read() == ap_const_lv5_8);
}

void des_dec::thread_empty_14_fu_808_p2() {
    empty_14_fu_808_p2 = (empty_13_fu_802_p2.read() | empty_12_fu_796_p2.read());
}

void des_dec::thread_empty_15_fu_814_p2() {
    empty_15_fu_814_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_393.read() == ap_const_lv5_1);
}

void des_dec::thread_empty_16_fu_820_p2() {
    empty_16_fu_820_p2 = (empty_15_fu_814_p2.read() | empty_14_fu_808_p2.read());
}

void des_dec::thread_empty_17_fu_826_p2() {
    empty_17_fu_826_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_393.read() == ap_const_lv5_0);
}

void des_dec::thread_empty_18_fu_832_p2() {
    empty_18_fu_832_p2 = (empty_17_fu_826_p2.read() | empty_16_fu_820_p2.read());
}

void des_dec::thread_empty_9_fu_559_p1() {
    empty_9_fu_559_p1 = i_0_0_reg_360.read().range(6-1, 0);
}

void des_dec::thread_f_function_res_fu_1396_p3() {
    f_function_res_fu_1396_p3 = esl_concat<31,1>(trunc_ln254_1_reg_1693.read(), trunc_ln254_fu_1392_p1.read());
}

void des_dec::thread_i_5_fu_1409_p2() {
    i_5_fu_1409_p2 = (!i_4_reg_517.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_4_reg_517.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void des_dec::thread_i_6_fu_790_p2() {
    i_6_fu_790_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_2_reg_393.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void des_dec::thread_i_7_fu_1013_p2() {
    i_7_fu_1013_p2 = (!i_3_reg_448.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_3_reg_448.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void des_dec::thread_i_fu_715_p2() {
    i_fu_715_p2 = (!i_1_reg_382.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_1_reg_382.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void des_dec::thread_icmp_ln171_fu_548_p2() {
    icmp_ln171_fu_548_p2 = (!i_0_0_reg_360.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_0_reg_360.read() == ap_const_lv7_40);
}

void des_dec::thread_icmp_ln182_fu_709_p2() {
    icmp_ln182_fu_709_p2 = (!i_1_reg_382.read().is_01() || !ap_const_lv6_38.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_382.read() == ap_const_lv6_38);
}

void des_dec::thread_icmp_ln192_fu_784_p2() {
    icmp_ln192_fu_784_p2 = (!i_2_reg_393.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_393.read() == ap_const_lv5_10);
}

void des_dec::thread_icmp_ln216_fu_960_p2() {
    icmp_ln216_fu_960_p2 = (!j_0_reg_416.read().is_01() || !ap_const_lv6_30.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_416.read() == ap_const_lv6_30);
}

void des_dec::thread_icmp_ln223_fu_1007_p2() {
    icmp_ln223_fu_1007_p2 = (!i_3_reg_448.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_3_reg_448.read() == ap_const_lv5_10);
}

void des_dec::thread_icmp_ln227_fu_1027_p2() {
    icmp_ln227_fu_1027_p2 = (!j_1_reg_472.read().is_01() || !ap_const_lv6_30.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_472.read() == ap_const_lv6_30);
}

void des_dec::thread_icmp_ln235_fu_1115_p2() {
    icmp_ln235_fu_1115_p2 = (!j_2_reg_483.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(j_2_reg_483.read() == ap_const_lv4_8);
}

void des_dec::thread_icmp_ln252_fu_1349_p2() {
    icmp_ln252_fu_1349_p2 = (!j_3_reg_506.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j_3_reg_506.read() == ap_const_lv6_20);
}

void des_dec::thread_icmp_ln267_fu_1403_p2() {
    icmp_ln267_fu_1403_p2 = (!i_4_reg_517.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_4_reg_517.read() == ap_const_lv7_40);
}

void des_dec::thread_inv_init_perm_res_fu_1443_p3() {
    inv_init_perm_res_fu_1443_p3 = esl_concat<63,1>(trunc_ln270_1_reg_1721.read(), trunc_ln270_fu_1439_p1.read());
}

void des_dec::thread_j_4_fu_966_p2() {
    j_4_fu_966_p2 = (!j_0_reg_416.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_0_reg_416.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void des_dec::thread_j_5_fu_1121_p2() {
    j_5_fu_1121_p2 = (!j_2_reg_483.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_2_reg_483.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void des_dec::thread_j_6_fu_1355_p2() {
    j_6_fu_1355_p2 = (!j_3_reg_506.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_3_reg_506.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void des_dec::thread_j_fu_1033_p2() {
    j_fu_1033_p2 = (!j_1_reg_472.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_1_reg_472.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void des_dec::thread_lshr_ln174_1_fu_649_p2() {
    lshr_ln174_1_fu_649_p2 = (!zext_ln174_1_fu_645_p1.read().is_01())? sc_lv<64>(): input_r.read() >> (unsigned short)zext_ln174_1_fu_645_p1.read().to_uint();
}

void des_dec::thread_lshr_ln174_2_fu_668_p2() {
    lshr_ln174_2_fu_668_p2 = (!zext_ln174_2_fu_664_p1.read().is_01())? sc_lv<64>(): input_r.read() >> (unsigned short)zext_ln174_2_fu_664_p1.read().to_uint();
}

void des_dec::thread_lshr_ln174_3_fu_687_p2() {
    lshr_ln174_3_fu_687_p2 = (!zext_ln174_3_fu_683_p1.read().is_01())? sc_lv<64>(): input_r.read() >> (unsigned short)zext_ln174_3_fu_683_p1.read().to_uint();
}

void des_dec::thread_lshr_ln174_fu_630_p2() {
    lshr_ln174_fu_630_p2 = (!zext_ln174_4_fu_626_p1.read().is_01())? sc_lv<64>(): input_r.read() >> (unsigned short)zext_ln174_4_fu_626_p1.read().to_uint();
}

void des_dec::thread_lshr_ln184_fu_768_p2() {
    lshr_ln184_fu_768_p2 = (!zext_ln184_fu_764_p1.read().is_01())? sc_lv<64>(): key.read() >> (unsigned short)zext_ln184_fu_764_p1.read().to_uint();
}

void des_dec::thread_lshr_ln218_fu_991_p2() {
    lshr_ln218_fu_991_p2 = (!zext_ln218_1_fu_987_p1.read().is_01())? sc_lv<56>(): tmp_9_reg_1573.read() >> (unsigned short)zext_ln218_1_fu_987_p1.read().to_uint();
}

void des_dec::thread_lshr_ln229_fu_1065_p2() {
    lshr_ln229_fu_1065_p2 = (!zext_ln229_1_fu_1061_p1.read().is_01())? sc_lv<32>(): temp_reg_427.read() >> (unsigned short)zext_ln229_1_fu_1061_p1.read().to_uint();
}

void des_dec::thread_lshr_ln240_1_fu_1224_p2() {
    lshr_ln240_1_fu_1224_p2 = (!zext_ln240_6_fu_1221_p1.read().is_01())? sc_lv<48>(): and_ln240_fu_1216_p2.read() >> (unsigned short)zext_ln240_6_fu_1221_p1.read().to_uint();
}

void des_dec::thread_lshr_ln240_fu_1210_p2() {
    lshr_ln240_fu_1210_p2 = (!zext_ln240_4_fu_1206_p1.read().is_01())? sc_lv<48>(): ap_const_lv48_840000000000 >> (unsigned short)zext_ln240_4_fu_1206_p1.read().to_uint();
}

void des_dec::thread_lshr_ln243_1_fu_1272_p2() {
    lshr_ln243_1_fu_1272_p2 = (!zext_ln243_fu_1269_p1.read().is_01())? sc_lv<47>(): and_ln243_fu_1264_p2.read() >> (unsigned short)zext_ln243_fu_1269_p1.read().to_uint();
}

void des_dec::thread_lshr_ln243_fu_1258_p2() {
    lshr_ln243_fu_1258_p2 = (!zext_ln240_3_fu_1202_p1.read().is_01())? sc_lv<47>(): ap_const_lv47_780000000000 >> (unsigned short)zext_ln240_3_fu_1202_p1.read().to_uint();
}

void des_dec::thread_lshr_ln254_fu_1386_p2() {
    lshr_ln254_fu_1386_p2 = (!zext_ln254_1_fu_1382_p1.read().is_01())? sc_lv<32>(): s_output_1_fu_188.read() >> (unsigned short)zext_ln254_1_fu_1382_p1.read().to_uint();
}

void des_dec::thread_lshr_ln270_fu_1434_p2() {
    lshr_ln270_fu_1434_p2 = (!zext_ln270_fu_1430_p1.read().is_01())? sc_lv<64>(): pre_output_reg_1609.read() >> (unsigned short)zext_ln270_fu_1430_p1.read().to_uint();
}

void des_dec::thread_or_ln171_1_fu_578_p2() {
    or_ln171_1_fu_578_p2 = (empty_9_fu_559_p1.read() | ap_const_lv6_2);
}

void des_dec::thread_or_ln171_2_fu_589_p2() {
    or_ln171_2_fu_589_p2 = (empty_9_fu_559_p1.read() | ap_const_lv6_3);
}

void des_dec::thread_or_ln171_fu_563_p2() {
    or_ln171_fu_563_p2 = (empty_9_fu_559_p1.read() | ap_const_lv6_1);
}

void des_dec::thread_or_ln1_fu_1000_p3() {
    or_ln1_fu_1000_p3 = esl_concat<63,1>(trunc_ln218_1_reg_1591.read(), trunc_ln218_fu_996_p1.read());
}

void des_dec::thread_or_ln241_fu_1242_p2() {
    or_ln241_fu_1242_p2 = (tmp_5_fu_1234_p3.read() | trunc_ln240_1_fu_1230_p1.read());
}

void des_dec::thread_or_ln_fu_696_p6() {
    or_ln_fu_696_p6 = esl_concat<63,1>(esl_concat<62,1>(esl_concat<61,1>(esl_concat<60,1>(trunc_ln173_reg_1471.read(), trunc_ln174_fu_635_p1.read()), trunc_ln171_fu_654_p1.read()), trunc_ln174_1_fu_673_p1.read()), trunc_ln174_2_fu_692_p1.read());
}

void des_dec::thread_permuted_choice_1_fu_777_p3() {
    permuted_choice_1_fu_777_p3 = esl_concat<63,1>(trunc_ln184_1_reg_1524.read(), trunc_ln184_fu_773_p1.read());
}

void des_dec::thread_pre_output_fu_1019_p3() {
    pre_output_fu_1019_p3 = esl_concat<32,32>(temp_reg_427.read(), L_0_reg_437.read());
}

void des_dec::thread_s_input_fu_1079_p3() {
    s_input_fu_1079_p3 = esl_concat<63,1>(trunc_ln229_1_fu_1075_p1.read(), trunc_ln229_fu_1071_p1.read());
}

void des_dec::thread_s_output_fu_1336_p3() {
    s_output_fu_1336_p3 = esl_concat<28,4>(trunc_ln246_1_fu_1332_p1.read(), S_q0.read());
}

void des_dec::thread_sext_ln240_fu_1199_p1() {
    sext_ln240_fu_1199_p1 = esl_sext<32,7>(sub_ln240_reg_1655.read());
}

void des_dec::thread_sext_ln246_1_fu_1296_p1() {
    sext_ln246_1_fu_1296_p1 = esl_sext<9,8>(trunc_ln246_fu_1292_p1.read());
}

void des_dec::thread_sext_ln246_2_fu_1306_p1() {
    sext_ln246_2_fu_1306_p1 = esl_sext<11,9>(add_ln246_fu_1300_p2.read());
}

void des_dec::thread_sext_ln246_3_fu_1328_p1() {
    sext_ln246_3_fu_1328_p1 = esl_sext<64,11>(add_ln246_1_reg_1670.read());
}

void des_dec::thread_sext_ln246_fu_1288_p1() {
    sext_ln246_fu_1288_p1 = esl_sext<9,8>(tmp_7_fu_1278_p4.read());
}

void des_dec::thread_shl_ln240_1_fu_1163_p3() {
    shl_ln240_1_fu_1163_p3 = esl_concat<3,2>(trunc_ln240_fu_1127_p1.read(), ap_const_lv2_0);
}

void des_dec::thread_shl_ln240_fu_1143_p2() {
    shl_ln240_fu_1143_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): j_2_reg_483.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void des_dec::thread_shl_ln_fu_1131_p3() {
    shl_ln_fu_1131_p3 = esl_concat<3,3>(trunc_ln240_fu_1127_p1.read(), ap_const_lv3_0);
}

void des_dec::thread_sub_key_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        sub_key_address0 =  (sc_lv<4>) (zext_ln232_fu_1050_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sub_key_address0 = sub_key_addr_reg_1561.read();
    } else {
        sub_key_address0 = "XXXX";
    }
}

void des_dec::thread_sub_key_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        sub_key_ce0 = ap_const_logic_1;
    } else {
        sub_key_ce0 = ap_const_logic_0;
    }
}

void des_dec::thread_sub_key_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sub_key_we0 = ap_const_logic_1;
    } else {
        sub_key_we0 = ap_const_logic_0;
    }
}

void des_dec::thread_sub_ln174_1_fu_639_p2() {
    sub_ln174_1_fu_639_p2 = (!ap_const_lv7_40.is_01() || !IP_q1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(IP_q1.read()));
}

void des_dec::thread_sub_ln174_2_fu_658_p2() {
    sub_ln174_2_fu_658_p2 = (!ap_const_lv7_40.is_01() || !IP_q2.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(IP_q2.read()));
}

void des_dec::thread_sub_ln174_3_fu_677_p2() {
    sub_ln174_3_fu_677_p2 = (!ap_const_lv7_40.is_01() || !IP_q3.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(IP_q3.read()));
}

void des_dec::thread_sub_ln174_fu_620_p2() {
    sub_ln174_fu_620_p2 = (!ap_const_lv7_40.is_01() || !IP_q0.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(IP_q0.read()));
}

void des_dec::thread_sub_ln184_fu_758_p2() {
    sub_ln184_fu_758_p2 = (!ap_const_lv7_40.is_01() || !zext_ln184_2_fu_754_p1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(zext_ln184_2_fu_754_p1.read()));
}

void des_dec::thread_sub_ln218_fu_981_p2() {
    sub_ln218_fu_981_p2 = (!ap_const_lv6_38.is_01() || !PC2_q0.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_38) - sc_biguint<6>(PC2_q0.read()));
}

void des_dec::thread_sub_ln229_fu_1055_p2() {
    sub_ln229_fu_1055_p2 = (!ap_const_lv6_20.is_01() || !E_q0.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_20) - sc_biguint<6>(E_q0.read()));
}

void des_dec::thread_sub_ln232_fu_1044_p2() {
    sub_ln232_fu_1044_p2 = (!ap_const_lv5_F.is_01() || !i_3_reg_448.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_F) - sc_biguint<5>(i_3_reg_448.read()));
}

void des_dec::thread_sub_ln240_1_fu_1175_p2() {
    sub_ln240_1_fu_1175_p2 = (!ap_const_lv6_2A.is_01() || !zext_ln240_1_fu_1149_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2A) - sc_biguint<6>(zext_ln240_1_fu_1149_p1.read()));
}

void des_dec::thread_sub_ln240_2_fu_1181_p2() {
    sub_ln240_2_fu_1181_p2 = (!sub_ln240_1_fu_1175_p2.read().is_01() || !zext_ln240_5_fu_1171_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln240_1_fu_1175_p2.read()) - sc_biguint<6>(zext_ln240_5_fu_1171_p1.read()));
}

void des_dec::thread_sub_ln240_fu_1157_p2() {
    sub_ln240_fu_1157_p2 = (!zext_ln240_fu_1139_p1.read().is_01() || !zext_ln240_2_fu_1153_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln240_fu_1139_p1.read()) - sc_biguint<7>(zext_ln240_2_fu_1153_p1.read()));
}

void des_dec::thread_sub_ln243_1_fu_1193_p2() {
    sub_ln243_1_fu_1193_p2 = (!sub_ln243_fu_1187_p2.read().is_01() || !zext_ln240_5_fu_1171_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln243_fu_1187_p2.read()) - sc_biguint<6>(zext_ln240_5_fu_1171_p1.read()));
}

void des_dec::thread_sub_ln243_fu_1187_p2() {
    sub_ln243_fu_1187_p2 = (!ap_const_lv6_2B.is_01() || !zext_ln240_1_fu_1149_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2B) - sc_biguint<6>(zext_ln240_1_fu_1149_p1.read()));
}

void des_dec::thread_sub_ln254_fu_1376_p2() {
    sub_ln254_fu_1376_p2 = (!ap_const_lv6_20.is_01() || !P_q0.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_20) - sc_biguint<6>(P_q0.read()));
}

void des_dec::thread_sub_ln270_fu_1424_p2() {
    sub_ln270_fu_1424_p2 = (!ap_const_lv7_40.is_01() || !PI_q0.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(PI_q0.read()));
}

void des_dec::thread_tmp_2_fu_892_p3() {
    tmp_2_fu_892_p3 = C_1_fu_180.read().range(27, 27);
}

void des_dec::thread_tmp_3_fu_842_p4() {
    tmp_3_fu_842_p4 = C_1_fu_180.read().range(27, 26);
}

void des_dec::thread_tmp_4_fu_912_p3() {
    tmp_4_fu_912_p3 = D_fu_184.read().range(27, 27);
}

void des_dec::thread_tmp_5_fu_1234_p3() {
    tmp_5_fu_1234_p3 = lshr_ln240_1_fu_1224_p2.read().range(4, 4);
}

void des_dec::thread_tmp_6_fu_1248_p4() {
    tmp_6_fu_1248_p4 = lshr_ln240_1_fu_1224_p2.read().range(7, 5);
}

void des_dec::thread_tmp_7_fu_1278_p4() {
    tmp_7_fu_1278_p4 = esl_concat<4,4>(esl_concat<3,1>(tmp_6_fu_1248_p4.read(), or_ln241_fu_1242_p2.read()), ap_const_lv4_0);
}

void des_dec::thread_tmp_8_fu_1310_p3() {
    tmp_8_fu_1310_p3 = esl_concat<4,6>(j_2_reg_483.read(), ap_const_lv6_0);
}

void des_dec::thread_tmp_9_fu_952_p3() {
    tmp_9_fu_952_p3 = esl_concat<28,28>(C_1_fu_180.read(), D_fu_184.read());
}

void des_dec::thread_tmp_s_fu_864_p4() {
    tmp_s_fu_864_p4 = D_fu_184.read().range(27, 26);
}

void des_dec::thread_trunc_ln171_fu_654_p1() {
    trunc_ln171_fu_654_p1 = lshr_ln174_1_fu_649_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln173_fu_569_p1() {
    trunc_ln173_fu_569_p1 = init_perm_res_0_0_reg_349.read().range(60-1, 0);
}

void des_dec::thread_trunc_ln174_1_fu_673_p1() {
    trunc_ln174_1_fu_673_p1 = lshr_ln174_2_fu_668_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln174_2_fu_692_p1() {
    trunc_ln174_2_fu_692_p1 = lshr_ln174_3_fu_687_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln174_fu_635_p1() {
    trunc_ln174_fu_635_p1 = lshr_ln174_fu_630_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln184_1_fu_726_p1() {
    trunc_ln184_1_fu_726_p1 = permuted_choice_1_0_reg_371.read().range(63-1, 0);
}

void des_dec::thread_trunc_ln184_fu_773_p1() {
    trunc_ln184_fu_773_p1 = lshr_ln184_fu_768_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln197_fu_900_p1() {
    trunc_ln197_fu_900_p1 = C_1_fu_180.read().range(27-1, 0);
}

void des_dec::thread_trunc_ln198_fu_920_p1() {
    trunc_ln198_fu_920_p1 = D_fu_184.read().range(27-1, 0);
}

void des_dec::thread_trunc_ln203_fu_838_p1() {
    trunc_ln203_fu_838_p1 = C_1_fu_180.read().range(26-1, 0);
}

void des_dec::thread_trunc_ln204_fu_860_p1() {
    trunc_ln204_fu_860_p1 = D_fu_184.read().range(26-1, 0);
}

void des_dec::thread_trunc_ln218_1_fu_977_p1() {
    trunc_ln218_1_fu_977_p1 = sub_key_load_1_reg_404.read().range(63-1, 0);
}

void des_dec::thread_trunc_ln218_fu_996_p1() {
    trunc_ln218_fu_996_p1 = lshr_ln218_fu_991_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln229_1_fu_1075_p1() {
    trunc_ln229_1_fu_1075_p1 = s_input_0_reg_460.read().range(63-1, 0);
}

void des_dec::thread_trunc_ln229_fu_1071_p1() {
    trunc_ln229_fu_1071_p1 = lshr_ln229_fu_1065_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln232_1_fu_1091_p1() {
    trunc_ln232_1_fu_1091_p1 = sub_key_q0.read().range(48-1, 0);
}

void des_dec::thread_trunc_ln232_2_fu_1095_p1() {
    trunc_ln232_2_fu_1095_p1 = s_input_0_reg_460.read().range(47-1, 0);
}

void des_dec::thread_trunc_ln232_3_fu_1099_p1() {
    trunc_ln232_3_fu_1099_p1 = sub_key_q0.read().range(47-1, 0);
}

void des_dec::thread_trunc_ln232_fu_1087_p1() {
    trunc_ln232_fu_1087_p1 = s_input_0_reg_460.read().range(48-1, 0);
}

void des_dec::thread_trunc_ln240_1_fu_1230_p1() {
    trunc_ln240_1_fu_1230_p1 = lshr_ln240_1_fu_1224_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln240_fu_1127_p1() {
    trunc_ln240_fu_1127_p1 = j_2_reg_483.read().range(3-1, 0);
}

void des_dec::thread_trunc_ln246_1_fu_1332_p1() {
    trunc_ln246_1_fu_1332_p1 = s_output_1_fu_188.read().range(28-1, 0);
}

void des_dec::thread_trunc_ln246_fu_1292_p1() {
    trunc_ln246_fu_1292_p1 = lshr_ln243_1_fu_1272_p2.read().range(8-1, 0);
}

void des_dec::thread_trunc_ln254_1_fu_1366_p1() {
    trunc_ln254_1_fu_1366_p1 = f_function_res_0_reg_495.read().range(31-1, 0);
}

void des_dec::thread_trunc_ln254_fu_1392_p1() {
    trunc_ln254_fu_1392_p1 = lshr_ln254_fu_1386_p2.read().range(1-1, 0);
}

void des_dec::thread_trunc_ln270_1_fu_1420_p1() {
    trunc_ln270_1_fu_1420_p1 = inv_init_perm_res_0_reg_528.read().range(63-1, 0);
}

void des_dec::thread_trunc_ln270_fu_1439_p1() {
    trunc_ln270_fu_1439_p1 = lshr_ln270_fu_1434_p2.read().range(1-1, 0);
}

void des_dec::thread_xor_ln232_1_fu_1109_p2() {
    xor_ln232_1_fu_1109_p2 = (trunc_ln232_1_fu_1091_p1.read() ^ trunc_ln232_fu_1087_p1.read());
}

void des_dec::thread_xor_ln232_fu_1103_p2() {
    xor_ln232_fu_1103_p2 = (trunc_ln232_3_fu_1099_p1.read() ^ trunc_ln232_2_fu_1095_p1.read());
}

void des_dec::thread_zext_ln174_1_fu_645_p1() {
    zext_ln174_1_fu_645_p1 = esl_zext<64,7>(sub_ln174_1_fu_639_p2.read());
}

void des_dec::thread_zext_ln174_2_fu_664_p1() {
    zext_ln174_2_fu_664_p1 = esl_zext<64,7>(sub_ln174_2_fu_658_p2.read());
}

void des_dec::thread_zext_ln174_3_fu_683_p1() {
    zext_ln174_3_fu_683_p1 = esl_zext<64,7>(sub_ln174_3_fu_677_p2.read());
}

void des_dec::thread_zext_ln174_4_fu_626_p1() {
    zext_ln174_4_fu_626_p1 = esl_zext<64,7>(sub_ln174_fu_620_p2.read());
}

void des_dec::thread_zext_ln174_5_fu_573_p1() {
    zext_ln174_5_fu_573_p1 = esl_zext<64,6>(or_ln171_fu_563_p2.read());
}

void des_dec::thread_zext_ln174_6_fu_584_p1() {
    zext_ln174_6_fu_584_p1 = esl_zext<64,6>(or_ln171_1_fu_578_p2.read());
}

void des_dec::thread_zext_ln174_7_fu_595_p1() {
    zext_ln174_7_fu_595_p1 = esl_zext<64,6>(or_ln171_2_fu_589_p2.read());
}

void des_dec::thread_zext_ln174_fu_554_p1() {
    zext_ln174_fu_554_p1 = esl_zext<64,7>(i_0_0_reg_360.read());
}

void des_dec::thread_zext_ln184_1_fu_721_p1() {
    zext_ln184_1_fu_721_p1 = esl_zext<64,6>(i_1_reg_382.read());
}

void des_dec::thread_zext_ln184_2_fu_754_p1() {
    zext_ln184_2_fu_754_p1 = esl_zext<7,6>(PC1_q0.read());
}

void des_dec::thread_zext_ln184_fu_764_p1() {
    zext_ln184_fu_764_p1 = esl_zext<64,7>(sub_ln184_fu_758_p2.read());
}

void des_dec::thread_zext_ln214_fu_942_p1() {
    zext_ln214_fu_942_p1 = esl_zext<64,5>(i_2_reg_393.read());
}

void des_dec::thread_zext_ln218_1_fu_987_p1() {
    zext_ln218_1_fu_987_p1 = esl_zext<56,6>(sub_ln218_fu_981_p2.read());
}

void des_dec::thread_zext_ln218_fu_972_p1() {
    zext_ln218_fu_972_p1 = esl_zext<64,6>(j_0_reg_416.read());
}

void des_dec::thread_zext_ln229_1_fu_1061_p1() {
    zext_ln229_1_fu_1061_p1 = esl_zext<32,6>(sub_ln229_fu_1055_p2.read());
}

void des_dec::thread_zext_ln229_fu_1039_p1() {
    zext_ln229_fu_1039_p1 = esl_zext<64,6>(j_1_reg_472.read());
}

void des_dec::thread_zext_ln232_fu_1050_p1() {
    zext_ln232_fu_1050_p1 = esl_zext<64,5>(sub_ln232_fu_1044_p2.read());
}

void des_dec::thread_zext_ln240_1_fu_1149_p1() {
    zext_ln240_1_fu_1149_p1 = esl_zext<6,4>(shl_ln240_fu_1143_p2.read());
}

void des_dec::thread_zext_ln240_2_fu_1153_p1() {
    zext_ln240_2_fu_1153_p1 = esl_zext<7,4>(shl_ln240_fu_1143_p2.read());
}

void des_dec::thread_zext_ln240_3_fu_1202_p1() {
    zext_ln240_3_fu_1202_p1 = esl_zext<47,32>(sext_ln240_fu_1199_p1.read());
}

void des_dec::thread_zext_ln240_4_fu_1206_p1() {
    zext_ln240_4_fu_1206_p1 = esl_zext<48,32>(sext_ln240_fu_1199_p1.read());
}

void des_dec::thread_zext_ln240_5_fu_1171_p1() {
    zext_ln240_5_fu_1171_p1 = esl_zext<6,5>(shl_ln240_1_fu_1163_p3.read());
}

void des_dec::thread_zext_ln240_6_fu_1221_p1() {
    zext_ln240_6_fu_1221_p1 = esl_zext<48,6>(sub_ln240_2_reg_1660.read());
}

void des_dec::thread_zext_ln240_fu_1139_p1() {
    zext_ln240_fu_1139_p1 = esl_zext<7,6>(shl_ln_fu_1131_p3.read());
}

void des_dec::thread_zext_ln243_fu_1269_p1() {
    zext_ln243_fu_1269_p1 = esl_zext<47,6>(sub_ln243_1_reg_1665.read());
}

void des_dec::thread_zext_ln246_fu_1318_p1() {
    zext_ln246_fu_1318_p1 = esl_zext<11,10>(tmp_8_fu_1310_p3.read());
}

void des_dec::thread_zext_ln254_1_fu_1382_p1() {
    zext_ln254_1_fu_1382_p1 = esl_zext<32,6>(sub_ln254_fu_1376_p2.read());
}

void des_dec::thread_zext_ln254_fu_1361_p1() {
    zext_ln254_fu_1361_p1 = esl_zext<64,6>(j_3_reg_506.read());
}

void des_dec::thread_zext_ln270_1_fu_1415_p1() {
    zext_ln270_1_fu_1415_p1 = esl_zext<64,7>(i_4_reg_517.read());
}

void des_dec::thread_zext_ln270_fu_1430_p1() {
    zext_ln270_fu_1430_p1 = esl_zext<64,7>(sub_ln270_fu_1424_p2.read());
}

void des_dec::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_548_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln182_fu_709_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln192_fu_784_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln216_fu_960_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln223_fu_1007_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln227_fu_1027_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln235_fu_1115_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 131072 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln252_fu_1349_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln267_fu_1403_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void des_dec::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r\" :  \"" << input_r.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"key\" :  \"" << key.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

