// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_unroll1_proc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_unroll1_proc::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_unroll1_proc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Loop_unroll1_proc::ap_ST_fsm_state1 = "1";
const sc_lv<3> Loop_unroll1_proc::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> Loop_unroll1_proc::ap_ST_fsm_state4 = "100";
const sc_lv<32> Loop_unroll1_proc::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_unroll1_proc::ap_const_boolean_1 = true;
const sc_lv<32> Loop_unroll1_proc::ap_const_lv32_1 = "1";
const bool Loop_unroll1_proc::ap_const_boolean_0 = false;
const sc_lv<1> Loop_unroll1_proc::ap_const_lv1_0 = "0";
const sc_lv<1> Loop_unroll1_proc::ap_const_lv1_1 = "1";
const sc_lv<64> Loop_unroll1_proc::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<7> Loop_unroll1_proc::ap_const_lv7_0 = "0000000";
const sc_lv<7> Loop_unroll1_proc::ap_const_lv7_40 = "1000000";
const sc_lv<7> Loop_unroll1_proc::ap_const_lv7_1 = "1";
const sc_lv<32> Loop_unroll1_proc::ap_const_lv32_2 = "10";

Loop_unroll1_proc::Loop_unroll1_proc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    IP_U = new Loop_unroll1_procbkb("IP_U");
    IP_U->clk(ap_clk);
    IP_U->reset(ap_rst);
    IP_U->address0(IP_address0);
    IP_U->ce0(IP_ce0);
    IP_U->q0(IP_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_IP_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln174_fu_102_p1 );

    SC_METHOD(thread_IP_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( input_r_empty_n );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln171_fu_90_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( init_perm_res_0_loc_s_reg_67 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_i_fu_96_p2);
    sensitive << ( i_0_i_i_i_reg_79 );

    SC_METHOD(thread_icmp_ln171_fu_90_p2);
    sensitive << ( i_0_i_i_i_reg_79 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_init_perm_res_fu_130_p3);
    sensitive << ( trunc_ln174_1_fu_126_p1 );
    sensitive << ( trunc_ln174_fu_122_p1 );

    SC_METHOD(thread_input_r_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_r_empty_n );

    SC_METHOD(thread_input_r_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_r_empty_n );

    SC_METHOD(thread_lshr_ln174_fu_117_p2);
    sensitive << ( input_read_reg_138 );
    sensitive << ( zext_ln174_1_fu_113_p1 );

    SC_METHOD(thread_sub_ln174_fu_107_p2);
    sensitive << ( IP_q0 );

    SC_METHOD(thread_trunc_ln174_1_fu_126_p1);
    sensitive << ( init_perm_res_0_loc_s_reg_67 );

    SC_METHOD(thread_trunc_ln174_fu_122_p1);
    sensitive << ( lshr_ln174_fu_117_p2 );

    SC_METHOD(thread_zext_ln174_1_fu_113_p1);
    sensitive << ( sub_ln174_fu_107_p2 );

    SC_METHOD(thread_zext_ln174_fu_102_p1);
    sensitive << ( i_0_i_i_i_reg_79 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_r_empty_n );
    sensitive << ( icmp_ln171_fu_90_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_unroll1_proc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_dout, "(port)input_r_dout");
    sc_trace(mVcdFile, input_r_empty_n, "(port)input_r_empty_n");
    sc_trace(mVcdFile, input_r_read, "(port)input_r_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, IP_address0, "IP_address0");
    sc_trace(mVcdFile, IP_ce0, "IP_ce0");
    sc_trace(mVcdFile, IP_q0, "IP_q0");
    sc_trace(mVcdFile, input_r_blk_n, "input_r_blk_n");
    sc_trace(mVcdFile, init_perm_res_0_loc_s_reg_67, "init_perm_res_0_loc_s_reg_67");
    sc_trace(mVcdFile, i_0_i_i_i_reg_79, "i_0_i_i_i_reg_79");
    sc_trace(mVcdFile, input_read_reg_138, "input_read_reg_138");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln171_fu_90_p2, "icmp_ln171_fu_90_p2");
    sc_trace(mVcdFile, icmp_ln171_reg_143, "icmp_ln171_reg_143");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_96_p2, "i_fu_96_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, init_perm_res_fu_130_p3, "init_perm_res_fu_130_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln174_fu_102_p1, "zext_ln174_fu_102_p1");
    sc_trace(mVcdFile, sub_ln174_fu_107_p2, "sub_ln174_fu_107_p2");
    sc_trace(mVcdFile, zext_ln174_1_fu_113_p1, "zext_ln174_1_fu_113_p1");
    sc_trace(mVcdFile, lshr_ln174_fu_117_p2, "lshr_ln174_fu_117_p2");
    sc_trace(mVcdFile, trunc_ln174_1_fu_126_p1, "trunc_ln174_1_fu_126_p1");
    sc_trace(mVcdFile, trunc_ln174_fu_122_p1, "trunc_ln174_fu_122_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Loop_unroll1_proc::~Loop_unroll1_proc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete IP_U;
}

void Loop_unroll1_proc::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln171_fu_90_p2.read(), ap_const_lv1_0))) {
        i_0_i_i_i_reg_79 = i_fu_96_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
        i_0_i_i_i_reg_79 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln171_reg_143.read(), ap_const_lv1_0))) {
        init_perm_res_0_loc_s_reg_67 = init_perm_res_fu_130_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
        init_perm_res_0_loc_s_reg_67 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln171_reg_143 = icmp_ln171_fu_90_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
        input_read_reg_138 = input_r_dout.read();
    }
}

void Loop_unroll1_proc::thread_IP_address0() {
    IP_address0 =  (sc_lv<6>) (zext_ln174_fu_102_p1.read());
}

void Loop_unroll1_proc::thread_IP_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        IP_ce0 = ap_const_logic_1;
    } else {
        IP_ce0 = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Loop_unroll1_proc::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_unroll1_proc::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void Loop_unroll1_proc::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_unroll1_proc::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_unroll1_proc::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_unroll1_proc::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read()));
}

void Loop_unroll1_proc::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_unroll1_proc::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_unroll1_proc::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln171_fu_90_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_unroll1_proc::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_unroll1_proc::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_ap_return() {
    ap_return = init_perm_res_0_loc_s_reg_67.read();
}

void Loop_unroll1_proc::thread_i_fu_96_p2() {
    i_fu_96_p2 = (!i_0_i_i_i_reg_79.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_i_i_i_reg_79.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void Loop_unroll1_proc::thread_icmp_ln171_fu_90_p2() {
    icmp_ln171_fu_90_p2 = (!i_0_i_i_i_reg_79.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_i_reg_79.read() == ap_const_lv7_40);
}

void Loop_unroll1_proc::thread_init_perm_res_fu_130_p3() {
    init_perm_res_fu_130_p3 = esl_concat<63,1>(trunc_ln174_1_fu_126_p1.read(), trunc_ln174_fu_122_p1.read());
}

void Loop_unroll1_proc::thread_input_r_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        input_r_blk_n = input_r_empty_n.read();
    } else {
        input_r_blk_n = ap_const_logic_1;
    }
}

void Loop_unroll1_proc::thread_input_r_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
        input_r_read = ap_const_logic_1;
    } else {
        input_r_read = ap_const_logic_0;
    }
}

void Loop_unroll1_proc::thread_lshr_ln174_fu_117_p2() {
    lshr_ln174_fu_117_p2 = (!zext_ln174_1_fu_113_p1.read().is_01())? sc_lv<64>(): input_read_reg_138.read() >> (unsigned short)zext_ln174_1_fu_113_p1.read().to_uint();
}

void Loop_unroll1_proc::thread_sub_ln174_fu_107_p2() {
    sub_ln174_fu_107_p2 = (!ap_const_lv7_40.is_01() || !IP_q0.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_40) - sc_biguint<7>(IP_q0.read()));
}

void Loop_unroll1_proc::thread_trunc_ln174_1_fu_126_p1() {
    trunc_ln174_1_fu_126_p1 = init_perm_res_0_loc_s_reg_67.read().range(63-1, 0);
}

void Loop_unroll1_proc::thread_trunc_ln174_fu_122_p1() {
    trunc_ln174_fu_122_p1 = lshr_ln174_fu_117_p2.read().range(1-1, 0);
}

void Loop_unroll1_proc::thread_zext_ln174_1_fu_113_p1() {
    zext_ln174_1_fu_113_p1 = esl_zext<64,7>(sub_ln174_fu_107_p2.read());
}

void Loop_unroll1_proc::thread_zext_ln174_fu_102_p1() {
    zext_ln174_fu_102_p1 = esl_zext<64,7>(i_0_i_i_i_reg_79.read());
}

void Loop_unroll1_proc::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, input_r_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln171_fu_90_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln171_fu_90_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

